//#line 2 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the gcop_ctrl package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __gcop_ctrl__MBSDMOCINTERFACECONFIG_H__
#define __gcop_ctrl__MBSDMOCINTERFACECONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace gcop_ctrl
{
  class MbsDMocInterfaceConfigStatics;
  
  class MbsDMocInterfaceConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(MbsDMocInterfaceConfig &config, const MbsDMocInterfaceConfig &max, const MbsDMocInterfaceConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const MbsDMocInterfaceConfig &config1, const MbsDMocInterfaceConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, MbsDMocInterfaceConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const MbsDMocInterfaceConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MbsDMocInterfaceConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const MbsDMocInterfaceConfig &config) const = 0;
      virtual void getValue(const MbsDMocInterfaceConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T MbsDMocInterfaceConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (MbsDMocInterfaceConfig::* field);

      virtual void clamp(MbsDMocInterfaceConfig &config, const MbsDMocInterfaceConfig &max, const MbsDMocInterfaceConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const MbsDMocInterfaceConfig &config1, const MbsDMocInterfaceConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, MbsDMocInterfaceConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const MbsDMocInterfaceConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MbsDMocInterfaceConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const MbsDMocInterfaceConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const MbsDMocInterfaceConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, MbsDMocInterfaceConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, MbsDMocInterfaceConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<MbsDMocInterfaceConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(MbsDMocInterfaceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("Nit"==(*i)->name){Nit = boost::any_cast<int>(val);}
        if("tf"==(*i)->name){tf = boost::any_cast<double>(val);}
        if("ureset"==(*i)->name){ureset = boost::any_cast<bool>(val);}
        if("final"==(*i)->name){final = boost::any_cast<bool>(val);}
        if("iterate"==(*i)->name){iterate = boost::any_cast<bool>(val);}
        if("animate"==(*i)->name){animate = boost::any_cast<bool>(val);}
        if("x"==(*i)->name){x = boost::any_cast<double>(val);}
        if("y"==(*i)->name){y = boost::any_cast<double>(val);}
        if("z"==(*i)->name){z = boost::any_cast<double>(val);}
        if("vx"==(*i)->name){vx = boost::any_cast<double>(val);}
        if("vy"==(*i)->name){vy = boost::any_cast<double>(val);}
        if("vz"==(*i)->name){vz = boost::any_cast<double>(val);}
        if("roll"==(*i)->name){roll = boost::any_cast<double>(val);}
        if("pitch"==(*i)->name){pitch = boost::any_cast<double>(val);}
        if("yaw"==(*i)->name){yaw = boost::any_cast<double>(val);}
        if("vroll"==(*i)->name){vroll = boost::any_cast<double>(val);}
        if("vpitch"==(*i)->name){vpitch = boost::any_cast<double>(val);}
        if("vyaw"==(*i)->name){vyaw = boost::any_cast<double>(val);}
        if("i_J"==(*i)->name){i_J = boost::any_cast<int>(val);}
        if("Ji"==(*i)->name){Ji = boost::any_cast<double>(val);}
        if("Jvi"==(*i)->name){Jvi = boost::any_cast<double>(val);}
        if("i_Q"==(*i)->name){i_Q = boost::any_cast<int>(val);}
        if("Qi"==(*i)->name){Qi = boost::any_cast<double>(val);}
        if("Qfi"==(*i)->name){Qfi = boost::any_cast<double>(val);}
        if("i_R"==(*i)->name){i_R = boost::any_cast<int>(val);}
        if("Ri"==(*i)->name){Ri = boost::any_cast<double>(val);}
        if("mu"==(*i)->name){mu = boost::any_cast<double>(val);}
      }
    }

    int Nit;
double tf;
bool ureset;
bool final;
bool iterate;
bool animate;
double x;
double y;
double z;
double vx;
double vy;
double vz;
double roll;
double pitch;
double yaw;
double vroll;
double vpitch;
double vyaw;
int i_J;
double Ji;
double Jvi;
int i_Q;
double Qi;
double Qfi;
int i_R;
double Ri;
double mu;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int Nit;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double tf;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool ureset;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool final;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool iterate;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      bool animate;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double x;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double y;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double z;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double vx;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double vy;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double vz;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double roll;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double pitch;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double yaw;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double vroll;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double vpitch;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double vyaw;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int i_J;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double Ji;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double Jvi;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int i_Q;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double Qi;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double Qfi;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      int i_R;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double Ri;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      double mu;
//#line 255 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("MbsDMocInterfaceConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const MbsDMocInterfaceConfig &__max__ = __getMax__();
      const MbsDMocInterfaceConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const MbsDMocInterfaceConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const MbsDMocInterfaceConfig &__getDefault__();
    static const MbsDMocInterfaceConfig &__getMax__();
    static const MbsDMocInterfaceConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const MbsDMocInterfaceConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void MbsDMocInterfaceConfig::ParamDescription<std::string>::clamp(MbsDMocInterfaceConfig &config, const MbsDMocInterfaceConfig &max, const MbsDMocInterfaceConfig &min) const
  {
    return;
  }

  class MbsDMocInterfaceConfigStatics
  {
    friend class MbsDMocInterfaceConfig;
    
    MbsDMocInterfaceConfigStatics()
    {
MbsDMocInterfaceConfig::GroupDescription<MbsDMocInterfaceConfig::DEFAULT, MbsDMocInterfaceConfig> Default("Default", "", 0, 0, true, &MbsDMocInterfaceConfig::groups);
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.Nit = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.Nit = 30;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.Nit = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<int>("Nit", "int", 2, "Number of iterations of dmoc", "", &MbsDMocInterfaceConfig::Nit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<int>("Nit", "int", 2, "Number of iterations of dmoc", "", &MbsDMocInterfaceConfig::Nit)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.tf = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.tf = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.tf = 5.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("tf", "double", 2, "Final Time", "", &MbsDMocInterfaceConfig::tf)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("tf", "double", 2, "Final Time", "", &MbsDMocInterfaceConfig::tf)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.ureset = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.ureset = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.ureset = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<bool>("ureset", "bool", 2, "reset control", "", &MbsDMocInterfaceConfig::ureset)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<bool>("ureset", "bool", 2, "reset control", "", &MbsDMocInterfaceConfig::ureset)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.final = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.final = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.final = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<bool>("final", "bool", 1, "Change final posn and joint", "", &MbsDMocInterfaceConfig::final)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<bool>("final", "bool", 1, "Change final posn and joint", "", &MbsDMocInterfaceConfig::final)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.iterate = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.iterate = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.iterate = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<bool>("iterate", "bool", 1, "Iterate mbs Nit times", "", &MbsDMocInterfaceConfig::iterate)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<bool>("iterate", "bool", 1, "Iterate mbs Nit times", "", &MbsDMocInterfaceConfig::iterate)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.animate = 0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.animate = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.animate = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<bool>("animate", "bool", 1, "Animate mbs 1 time", "", &MbsDMocInterfaceConfig::animate)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<bool>("animate", "bool", 1, "Animate mbs 1 time", "", &MbsDMocInterfaceConfig::animate)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.x = -10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.x = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.x = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("x", "double", 2, "base xposn", "", &MbsDMocInterfaceConfig::x)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("x", "double", 2, "base xposn", "", &MbsDMocInterfaceConfig::x)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.y = -10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.y = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.y = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("y", "double", 2, "base yposn", "", &MbsDMocInterfaceConfig::y)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("y", "double", 2, "base yposn", "", &MbsDMocInterfaceConfig::y)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.z = -10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.z = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.z = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("z", "double", 2, "base zposn", "", &MbsDMocInterfaceConfig::z)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("z", "double", 2, "base zposn", "", &MbsDMocInterfaceConfig::z)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.vx = -1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.vx = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.vx = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vx", "double", 2, "base body xvel", "", &MbsDMocInterfaceConfig::vx)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vx", "double", 2, "base body xvel", "", &MbsDMocInterfaceConfig::vx)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.vy = -1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.vy = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.vy = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vy", "double", 2, "base body yvel", "", &MbsDMocInterfaceConfig::vy)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vy", "double", 2, "base body yvel", "", &MbsDMocInterfaceConfig::vy)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.vz = -1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.vz = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.vz = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vz", "double", 2, "base body zvel", "", &MbsDMocInterfaceConfig::vz)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vz", "double", 2, "base body zvel", "", &MbsDMocInterfaceConfig::vz)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.roll = -3.15;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.roll = 3.15;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.roll = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("roll", "double", 2, "base roll", "", &MbsDMocInterfaceConfig::roll)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("roll", "double", 2, "base roll", "", &MbsDMocInterfaceConfig::roll)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.pitch = -3.15;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.pitch = 3.15;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.pitch = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("pitch", "double", 2, "base pitch", "", &MbsDMocInterfaceConfig::pitch)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("pitch", "double", 2, "base pitch", "", &MbsDMocInterfaceConfig::pitch)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.yaw = -3.15;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.yaw = 3.15;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.yaw = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("yaw", "double", 2, "base yaw", "", &MbsDMocInterfaceConfig::yaw)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("yaw", "double", 2, "base yaw", "", &MbsDMocInterfaceConfig::yaw)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.vroll = -1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.vroll = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.vroll = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vroll", "double", 2, "base rollvel", "", &MbsDMocInterfaceConfig::vroll)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vroll", "double", 2, "base rollvel", "", &MbsDMocInterfaceConfig::vroll)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.vpitch = -1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.vpitch = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.vpitch = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vpitch", "double", 2, "base pitchvel", "", &MbsDMocInterfaceConfig::vpitch)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vpitch", "double", 2, "base pitchvel", "", &MbsDMocInterfaceConfig::vpitch)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.vyaw = -1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.vyaw = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.vyaw = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vyaw", "double", 2, "base yawvel", "", &MbsDMocInterfaceConfig::vyaw)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("vyaw", "double", 2, "base yawvel", "", &MbsDMocInterfaceConfig::vyaw)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.i_J = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.i_J = 40;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.i_J = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<int>("i_J", "int", 1, "Joint index starting with 1", "", &MbsDMocInterfaceConfig::i_J)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<int>("i_J", "int", 1, "Joint index starting with 1", "", &MbsDMocInterfaceConfig::i_J)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.Ji = -3.15;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.Ji = 3.15;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.Ji = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Ji", "double", 2, "Jointangle", "", &MbsDMocInterfaceConfig::Ji)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Ji", "double", 2, "Jointangle", "", &MbsDMocInterfaceConfig::Ji)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.Jvi = -1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.Jvi = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.Jvi = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Jvi", "double", 2, "Jointanglevel", "", &MbsDMocInterfaceConfig::Jvi)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Jvi", "double", 2, "Jointanglevel", "", &MbsDMocInterfaceConfig::Jvi)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.i_Q = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.i_Q = 40;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.i_Q = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<int>("i_Q", "int", 1, "StateCost_index starting with 1", "", &MbsDMocInterfaceConfig::i_Q)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<int>("i_Q", "int", 1, "StateCost_index starting with 1", "", &MbsDMocInterfaceConfig::i_Q)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.Qi = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.Qi = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.Qi = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Qi", "double", 2, "Statecost", "", &MbsDMocInterfaceConfig::Qi)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Qi", "double", 2, "Statecost", "", &MbsDMocInterfaceConfig::Qi)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.Qfi = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.Qfi = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.Qfi = 50.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Qfi", "double", 2, "FinStatecost", "", &MbsDMocInterfaceConfig::Qfi)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Qfi", "double", 2, "FinStatecost", "", &MbsDMocInterfaceConfig::Qfi)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.i_R = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.i_R = 40;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.i_R = 1;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<int>("i_R", "int", 1, "ControlCost_index starting with 1", "", &MbsDMocInterfaceConfig::i_R)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<int>("i_R", "int", 1, "ControlCost_index starting with 1", "", &MbsDMocInterfaceConfig::i_R)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.Ri = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.Ri = 10.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.Ri = 1.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Ri", "double", 2, "Controlcost", "", &MbsDMocInterfaceConfig::Ri)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("Ri", "double", 2, "Controlcost", "", &MbsDMocInterfaceConfig::Ri)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __min__.mu = 0.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __max__.mu = 100.0;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __default__.mu = 0.001;
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("mu", "double", 2, "Regularization constant", "", &MbsDMocInterfaceConfig::mu)));
//#line 259 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr(new MbsDMocInterfaceConfig::ParamDescription<double>("mu", "double", 2, "Regularization constant", "", &MbsDMocInterfaceConfig::mu)));
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/fuerte/stacks/dynamic_reconfigure/src/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(MbsDMocInterfaceConfig::AbstractGroupDescriptionConstPtr(new MbsDMocInterfaceConfig::GroupDescription<MbsDMocInterfaceConfig::DEFAULT, MbsDMocInterfaceConfig>(Default)));
//#line 390 "/opt/ros/fuerte/stacks/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<MbsDMocInterfaceConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<MbsDMocInterfaceConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    MbsDMocInterfaceConfig __max__;
    MbsDMocInterfaceConfig __min__;
    MbsDMocInterfaceConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const MbsDMocInterfaceConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static MbsDMocInterfaceConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &MbsDMocInterfaceConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const MbsDMocInterfaceConfig &MbsDMocInterfaceConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const MbsDMocInterfaceConfig &MbsDMocInterfaceConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const MbsDMocInterfaceConfig &MbsDMocInterfaceConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<MbsDMocInterfaceConfig::AbstractParamDescriptionConstPtr> &MbsDMocInterfaceConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<MbsDMocInterfaceConfig::AbstractGroupDescriptionConstPtr> &MbsDMocInterfaceConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const MbsDMocInterfaceConfigStatics *MbsDMocInterfaceConfig::__get_statics__()
  {
    const static MbsDMocInterfaceConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = MbsDMocInterfaceConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __MBSDMOCINTERFACERECONFIGURATOR_H__
