GCOP: lib/est/camera.cc File Reference
camera.cc File Reference
#include "camera.h"
#include <stdio.h>
#include <string.h>
#include <limits>
Defines
#define FLIP_AXIS
#define FLIP_AXIS
Functions
static double area (const Point &a, const Point &b, const Point &c)
static bool inters (const Point &a, const Point &b, const Point &c, const Point &d)
static void swap (Point &a, Point &b)
Define Documentation
#define FLIP_AXIS
#define FLIP_AXIS
Function Documentation
static double area (const Point & a, const Point & b, const Point & c) [static]
Referenced by inters(), and gcop::Camera::Pose().
static bool inters (const Point & a, const Point & b, const Point & c, const Point & d) [static]
References area().
Referenced by gcop::Camera::Pose().
static void swap (Point & a, Point & b) [static]
Referenced by gcop::Camera::Pose().