GCOP: gcop::UuvManifold Class Reference
gcop::UuvManifold Class Reference
#include <uuvmanifold.h>
Public Member Functions
void Lift (Vector12d &v, const UuvState &xa, const UuvState &xb)
void Retract (UuvState &xb, const UuvState &xa, const Vector12d &v)
void dtau (Matrix12d &M, const Vector12d &v)
void Adtau (Matrix12d &M, const Vector12d &v)
Static Public Member Functions
static UuvManifold & Instance ()
Member Function Documentation
void UuvManifold::Adtau (Matrix12d & M, const Vector12d & v)
References Instance().
void UuvManifold::dtau (Matrix12d & M, const Vector12d & v)
References Instance().
UuvManifold & UuvManifold::Instance () [static]
Referenced by Adtau(), dtau(), Lift(), and Retract().
void UuvManifold::Lift (Vector12d & v, const UuvState & xa, const UuvState & xb)
References gcop::UuvState::g, Instance(), and gcop::UuvState::v.
void UuvManifold::Retract (UuvState & xb, const UuvState & xa, const Vector12d & v)
References gcop::UuvState::g, Instance(), and gcop::UuvState::v.
The documentation for this class was generated from the following files:
lib/systems/manifolds/uuvmanifold.h
lib/systems/manifolds/uuvmanifold.cc