GCOP: gcop::ImuManifold Class Reference
gcop::ImuManifold Class Reference
#include <imumanifold.h>
Public Member Functions
void Lift (Vector9d &v, const ImuState &xa, const ImuState &xb)
void Retract (ImuState &xb, const ImuState &xa, const Vector9d &v)
void dtau (Matrix9d &M, const Vector9d &v)
void Adtau (Matrix9d &M, const Vector9d &v)
Static Public Member Functions
static ImuManifold & Instance ()
Member Function Documentation
void ImuManifold::Adtau (Matrix9d & M, const Vector9d & v)
References Instance().
void ImuManifold::dtau (Matrix9d & M, const Vector9d & v)
References Instance().
ImuManifold & ImuManifold::Instance () [static]
Referenced by Adtau(), dtau(), Lift(), and Retract().
void ImuManifold::Lift (Vector9d & v, const ImuState & xa, const ImuState & xb)
References gcop::ImuState::ba, gcop::ImuState::bg, Instance(), and gcop::ImuState::R.
void ImuManifold::Retract (ImuState & xb, const ImuState & xa, const Vector9d & v)
References gcop::ImuState::ba, gcop::ImuState::bg, Instance(), and gcop::ImuState::R.
The documentation for this class was generated from the following files:
lib/systems/manifolds/imumanifold.h
lib/systems/manifolds/imumanifold.cc