GCOP: gcop::AirplaneView Class Reference
gcop::AirplaneView Class Reference
#include <airplaneview.h>
Public Member Functions
AirplaneView (const Gunicycle &sys, vector< pair< Matrix3d, Vector2d > > *xs=0, vector< Vector2d > *us=0)
virtual ~AirplaneView ()
void Render (const pair< Matrix3d, Vector2d > *x, const Vector2d *u=0)
void Render (const vector< pair< Matrix3d, Vector2d > > *xs, const vector< Vector2d > *us=0, bool rs=true, int is=-1, int ie=-1, int dis=1, int dit=1, bool dl=false)
Public Attributes
const Gunicycle & sys
GLUquadricObj * qobj
Constructor & Destructor Documentation
AirplaneView::AirplaneView (const Gunicycle & sys, vector< pair< Matrix3d, Vector2d > > * xs = 0, vector< Vector2d > * us = 0)
Create a particle view of trajectory traj
Parameters:
sys particle
xs trajectory
References gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::lineWidth, qobj, and gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::rgba.
AirplaneView::~AirplaneView () [virtual]
References qobj.
Member Function Documentation
void AirplaneView::Render (const pair< Matrix3d, Vector2d > * x, const Vector2d * u = 0) [virtual]
Implements gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >.
References gcop::Gunicycle::dx, gcop::SE2::g2q(), gcop::SE2::Instance(), qobj, gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::SetColor(), and sys.
void AirplaneView::Render (const vector< pair< Matrix3d, Vector2d > > * xs, const vector< Vector2d > * us = 0, bool rs = true, int is = -1, int ie = -1, int dis = 1, int dit = 1, bool dl = false) [virtual]
Render a trajectory
Parameters:
traj trajectory
rs render state
is start index
ie end index
dis index step for rendering bodies along trajectory
dit index step for rendering states(points) along trajectory
dl always draw last state
Implements gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >.
References gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::dis, gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::dit, gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::lineWidth, gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::Render(), gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::rgba, gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::SetColor(), and gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >::xs.
Member Data Documentation
GLUquadricObj* gcop::AirplaneView::qobj
Referenced by AirplaneView(), Render(), and ~AirplaneView().
const Gunicycle& gcop::AirplaneView::sys
Referenced by Render().
The documentation for this class was generated from the following files:
lib/views/airplaneview.h
lib/views/airplaneview.cc