GCOP: gcop_urdf::Visual Class Reference
gcop_urdf::Visual Class Reference
#include <urdflink.h>
Public Member Functions
Visual ()
void clear ()
bool initXml (TiXmlElement *config)
Public Attributes
Pose origin
boost::shared_ptr< Geometry > geometry
std::string material_name
boost::shared_ptr< Material > material
std::string group_name
Constructor & Destructor Documentation
gcop_urdf::Visual::Visual () [inline]
References clear().
Member Function Documentation
void gcop_urdf::Visual::clear () [inline]
References gcop_urdf::Pose::clear(), geometry, group_name, material, material_name, and origin.
Referenced by Visual().
bool gcop_urdf::Visual::initXml (TiXmlElement * config)
Member Data Documentation
boost::shared_ptr<Geometry> gcop_urdf::Visual::geometry
Referenced by clear().
std::string gcop_urdf::Visual::group_name
Referenced by clear().
boost::shared_ptr<Material> gcop_urdf::Visual::material
Referenced by clear().
std::string gcop_urdf::Visual::material_name
Referenced by clear().
Pose gcop_urdf::Visual::origin
Referenced by clear().
The documentation for this class was generated from the following file:
lib/utils/urdflink.h