GCOP: gcop::View Class Reference
gcop::View Class Reference
#include <view.h>
Public Member Functions
View (const char *name=0)
virtual ~View ()
virtual void Render ()
virtual bool RenderFrame (int i=0)
void Lock ()
void Unlock ()
Protected Attributes
char name [256]
name
int id
id
pthread_mutex_t mut
synchronization
Friends
class Viewer
Detailed Description
Basic view class that all views should subclass. Render() should provide the rendering. Lock() and Unlock() should be used when any data used in Render() is being updated.
Author: Marin Kobilarov -- Copyright (C) 2005
Constructor & Destructor Documentation
View::View (const char * name = 0)
Create a view. All subclasses should call the constructor
Parameters:
name optional name
References mut, and s_view_id.
View::~View () [virtual]
Destroy view
References mut.
Member Function Documentation
void View::Lock ()
Lock a view. This is done when updating data inside this object. While a view is locked Render() is not called
References mut.
Referenced by gcop::Viewer::RenderViews().
void View::Render () [virtual]
Render a view: all subclasses should provide this method
Reimplemented in gcop::SystemView< Tx, Tu >, gcop::SystemView< Matrix3d, Vector3d >, gcop::SystemView< Vector5d, Vector2d >, gcop::SystemView< Matrix4d, Matrix< double, _nu, 1 > >, gcop::SystemView< Normal< _n >, Vector2d >, gcop::SystemView< UuvState, Matrix< double, c, 1 > >, gcop::SystemView< pair< Matrix3d, Vector9d >, Matrix< double, c, 1 > >, gcop::SystemView< MbsState, VectorXd >, gcop::SystemView< pair< Matrix3d, Vector3d >, Vector3d >, gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >, gcop::SystemView< Vector4d, Vector2d >, gcop::Kinbody3dTrackView< _nu >, gcop::PlotView, gcop::Body2dTrackView, gcop::Body3dTrackView, gcop::Body2dGraphView, gcop::Posegraph2dView, and gcop::DemView.
References RenderFrame().
Referenced by gcop::Viewer::RenderViews().
bool View::RenderFrame (int i = 0) [virtual]
Render a view: all subclasses should provide this method
Parameters:
i frame #
Returns:
return true if more frames should be rendered
Reimplemented in gcop::SystemView< Tx, Tu >, gcop::SystemView< Matrix3d, Vector3d >, gcop::SystemView< Vector5d, Vector2d >, gcop::SystemView< Matrix4d, Matrix< double, _nu, 1 > >, gcop::SystemView< Normal< _n >, Vector2d >, gcop::SystemView< UuvState, Matrix< double, c, 1 > >, gcop::SystemView< pair< Matrix3d, Vector9d >, Matrix< double, c, 1 > >, gcop::SystemView< MbsState, VectorXd >, gcop::SystemView< pair< Matrix3d, Vector3d >, Vector3d >, gcop::SystemView< pair< Matrix3d, Vector2d >, Vector2d >, gcop::SystemView< Vector4d, Vector2d >, gcop::Geom3dView, gcop::Kinbody3dTrackView< _nu >, gcop::Body2dTrackView, gcop::Body3dTrackView, gcop::Body2dGraphView, gcop::Posegraph2dView, and gcop::DemView.
References name.
Referenced by Render(), and gcop::Viewer::RenderViews().
void View::Unlock ()
Unlock the view and continue display
References mut.
Referenced by gcop::Viewer::RenderViews().
Friends And Related Function Documentation
friend class Viewer [friend]
Member Data Documentation
int gcop::View::id [protected]
id
Referenced by gcop::Viewer::Add(), and gcop::Viewer::Remove().
pthread_mutex_t gcop::View::mut [protected]
synchronization
Referenced by Lock(), Unlock(), View(), and ~View().
char gcop::View::name[256] [protected]
name
The view can optionally specify
Referenced by RenderFrame().
The documentation for this class was generated from the following files:
lib/views/view.h
lib/views/view.cc