GCOP: gcop::Imu Class Reference
gcop::Imu Class Reference
#include <imu.h>
Public Member Functions
Imu ()
virtual ~Imu ()
double Step (ImuState &xb, double t, const ImuState &xa, const Vector3d &u, double h, const VectorXd *p=0, Matrix9d *A=0, Matrix93d *B=0, Matrix9Xd *C=0)
bool Noise (Matrix9d &Q, double t, const ImuState &x, const Vector3d &u, double dt, const VectorXd *p=0)
Public Attributes
double sv
gyro bias white noise stdev (spectral density)
double su
gyro bias rate-of-change white noise stdev (spectral density)
double sa
acceleration bias rate-of-change white noise stdev (spectral density)
Detailed Description
An IMU system
Author: Marin Kobilarov marin(at)jhu.edu
Constructor & Destructor Documentation
Imu::Imu ()
References sa, su, and sv.
Imu::~Imu () [virtual]
Member Function Documentation
bool Imu::Noise (Matrix9d & Q, double t, const ImuState & x, const Vector3d & u, double dt, const VectorXd * p = 0)
References sa, su, and sv.
double Imu::Step (ImuState & xb, double t, const ImuState & xa, const Vector3d & u, double h, const VectorXd * p = 0, Matrix9d * A = 0, Matrix93d * B = 0, Matrix9Xd * C = 0)
References gcop::ImuState::ba, gcop::ImuState::bg, gcop::SO3::dexp(), gcop::SO3::exp(), gcop::SO3::Instance(), and gcop::ImuState::R.
Member Data Documentation
double gcop::Imu::sa
acceleration bias rate-of-change white noise stdev (spectral density)
Referenced by Imu(), and Noise().
double gcop::Imu::su
gyro bias rate-of-change white noise stdev (spectral density)
Referenced by Imu(), and Noise().
double gcop::Imu::sv
gyro bias white noise stdev (spectral density)
Referenced by Imu(), and Noise().
The documentation for this class was generated from the following files:
lib/systems/imu.h
lib/systems/imu.cc