GCOP: gcop::Body3dManifold Class Reference
gcop::Body3dManifold Class Reference
#include <body3dmanifold.h>
Public Member Functions
void Lift (Vector12d &v, const Body3dState &xa, const Body3dState &xb)
void Retract (Body3dState &xb, const Body3dState &xa, const Vector12d &v)
void dtau (Matrix12d &M, const Vector12d &v)
void Adtau (Matrix12d &M, const Vector12d &v)
Static Public Member Functions
static Body3dManifold & Instance ()
Member Function Documentation
void Body3dManifold::Adtau (Matrix12d & M, const Vector12d & v)
References Instance().
void Body3dManifold::dtau (Matrix12d & M, const Vector12d & v)
References Instance().
Body3dManifold & Body3dManifold::Instance () [static]
Referenced by Adtau(), dtau(), Lift(), and Retract().
void Body3dManifold::Lift (Vector12d & v, const Body3dState & xa, const Body3dState & xb)
References Instance().
void Body3dManifold::Retract (Body3dState & xb, const Body3dState & xa, const Vector12d & v)
References Instance().
The documentation for this class was generated from the following files:
lib/systems/manifolds/body3dmanifold.h
lib/systems/manifolds/body3dmanifold.cc