GCOP: gcop::Gunicycle Class Reference
gcop::Gunicycle Class Reference
#include <gunicycle.h>
Public Member Functions
Gunicycle ()
double Step (M3V2d &xb, double t, const M3V2d &xa, const Vector2d &u, double h, const VectorXd *p, Matrix5d *A=0, Matrix52d *B=0, Matrix5Xd *C=0)
Public Attributes
double dx
distance between left and right tires
double dy
distance between front and back axles
Detailed Description
A "geometric" unicycle model with 2nd order dynamics. This is often used to model simple wheeled robots or fixed-wing aircraft. The control system is implemented as an evolution on SE(2) as opposed to a vector space.
The state is where is the pose, the controls correspond to turn rate acceleration and forward acceleration.
Author: Marin Kobilarov marin(at)jhu.edu
Constructor & Destructor Documentation
Gunicycle::Gunicycle ()
Member Function Documentation
double Gunicycle::Step (M3V2d & xb, double t, const M3V2d & xa, const Vector2d & u, double h, const VectorXd * p, Matrix5d * A = 0, Matrix52d * B = 0, Matrix5Xd * C = 0)
References gcop::SE2::Ad(), gcop::SE2::cay(), gcop::SE2::dcay(), and gcop::SE2::Instance().
Member Data Documentation
double gcop::Gunicycle::dx
distance between left and right tires
Referenced by gcop::AirplaneView::Render(), and gcop::GunicycleView::Render().
double gcop::Gunicycle::dy
distance between front and back axles
The documentation for this class was generated from the following files:
lib/systems/gunicycle.h
lib/systems/gunicycle.cc