GCOP: gcop::Body2dView< c > Class Template Reference
gcop::Body2dView< c > Class Template Reference
#include <body2dview.h>
Public Types
typedef Matrix< double, c, 1 > Vectorcd
Public Member Functions
Body2dView (const Body2d< c > &sys)
Body2dView (const Body2d< c > &sys, vector< Body2dState > *xs=0, vector< Vectorcd > *us=0)
virtual ~Body2dView ()
void Render (const pair< Matrix3d, Vector3d > *x, const Vectorcd *u=0)
void Render (const vector< pair< Matrix3d, Vector3d > > *xs, const vector< Vectorcd > *us=0, bool rs=true, int is=-1, int ie=-1, int dis=1, int dit=1, bool dl=false)
Public Attributes
const Body2d< c > & sys
GLUquadricObj * qobj
double forceScale
force arrow scaling coefficient
template<int c = 3>
class gcop::Body2dView< c >
Member Typedef Documentation
template<int c = 3> typedef Matrix<double, c, 1> gcop::Body2dView< c >::Vectorcd
Constructor & Destructor Documentation
template<int c> gcop::Body2dView< c >::Body2dView (const Body2d< c > & sys)
Create a particle view of trajectory traj
Parameters:
sys particle
References gcop::Body2dView< c >::forceScale, gcop::SystemView< Body2dState, Matrix< double, c, 1 > >::lineWidth, gcop::Body2dView< c >::qobj, and gcop::SystemView< Body2dState, Matrix< double, c, 1 > >::rgba.
template<int c> gcop::Body2dView< c >::Body2dView (const Body2d< c > & sys, vector< Body2dState > * xs = 0, vector< Vectorcd > * us = 0)
Create a particle view of trajectory traj
Parameters:
sys particle
xs trajectory
References gcop::Body2dView< c >::forceScale, gcop::SystemView< Body2dState, Matrix< double, c, 1 > >::lineWidth, gcop::Body2dView< c >::qobj, and gcop::SystemView< Body2dState, Matrix< double, c, 1 > >::rgba.
template<int c> gcop::Body2dView< c >::~Body2dView () [virtual]
References gcop::Body2dView< c >::qobj.
Member Function Documentation
template<int c> void gcop::Body2dView< c >::Render (const pair< Matrix3d, Vector3d > * x, const Vectorcd * u = 0) [virtual]
Implements gcop::SystemView< Body2dState, Matrix< double, c, 1 > >.
References gcop::Viewer::DrawArrow(), gcop::SE2::g2q(), gcop::SE2::Instance(), and gcop::RenderUuv().
template<int c> void gcop::Body2dView< c >::Render (const vector< pair< Matrix3d, Vector3d > > * xs, const vector< Vectorcd > * us = 0, bool rs = true, int is = -1, int ie = -1, int dis = 1, int dit = 1, bool dl = false) [virtual]
Render a trajectory
Parameters:
traj trajectory
rs render state
is start index
ie end index
dis index step for rendering bodies along trajectory
dit index step for rendering states(points) along trajectory
dl always draw last state
Implements gcop::SystemView< Body2dState, Matrix< double, c, 1 > >.
Member Data Documentation
template<int c = 3> double gcop::Body2dView< c >::forceScale
force arrow scaling coefficient
Referenced by gcop::Body2dView< c >::Body2dView().
template<int c = 3> GLUquadricObj* gcop::Body2dView< c >::qobj
Referenced by gcop::Body2dView< c >::Body2dView(), and gcop::Body2dView< c >::~Body2dView().
template<int c = 3> const Body2d<c>& gcop::Body2dView< c >::sys
The documentation for this class was generated from the following files:
lib/views/body2dview.h
lib/views/body2dview.cc