GCOP: gcop::Kinbody2dManifold Class Reference
gcop::Kinbody2dManifold Class Reference
#include <kinbody2dmanifold.h>
Public Member Functions
void Lift (Vector3d &v, const Matrix3d &xa, const Matrix3d &xb)
void Retract (Matrix3d &xb, const Matrix3d &xa, const Vector3d &v)
void dtau (Matrix3d &M, const Vector3d &v)
void Adtau (Matrix3d &M, const Vector3d &v)
Static Public Member Functions
static Kinbody2dManifold & Instance ()
Member Function Documentation
void Kinbody2dManifold::Adtau (Matrix3d & M, const Vector3d & v)
void Kinbody2dManifold::dtau (Matrix3d & M, const Vector3d & v)
Kinbody2dManifold & Kinbody2dManifold::Instance () [static]
Referenced by Lift(), and Retract().
void Kinbody2dManifold::Lift (Vector3d & v, const Matrix3d & xa, const Matrix3d & xb)
References Instance().
void Kinbody2dManifold::Retract (Matrix3d & xb, const Matrix3d & xa, const Vector3d & v)
References Instance().
The documentation for this class was generated from the following files:
lib/systems/manifolds/kinbody2dmanifold.h
lib/systems/manifolds/kinbody2dmanifold.cc