GCOP: gcop::Kinbody3dView< _nu > Class Template Reference
gcop::Kinbody3dView< _nu > Class Template Reference
#include <kinbody3dview.h>
Public Member Functions
Kinbody3dView (const Kinbody3d< _nu > &sys)
Kinbody3dView (const Kinbody3d< _nu > &sys, vector< Matrix4d > *xs, vector< Vectorud > *us=0)
virtual ~Kinbody3dView ()
virtual void Render (const Matrix4d *x, const Vectorud *u=0)
void Render (const vector< Matrix4d > *xs, const vector< Vectorud > *us=0, bool rs=true, int is=-1, int ie=-1, int dis=1, int dit=1, bool dl=false)
Static Public Member Functions
static void Transform (const Matrix3d &R, const Vector3d &p)
Public Attributes
const Kinbody3d< _nu > & sys
GLUquadricObj * qobj
double dirSize
template<int _nu = 6>
class gcop::Kinbody3dView< _nu >
Constructor & Destructor Documentation
template<int _nu> Kinbody3dView::Kinbody3dView (const Kinbody3d< _nu > & sys)
Create a particle view of trajectory traj
Parameters:
sys particle
References gcop::Kinbody3dView< _nu >::dirSize, gcop::SystemView< Matrix4d, Matrix< double, _nu, 1 > >::lineWidth, gcop::Kinbody3dView< _nu >::qobj, and gcop::SystemView< Matrix4d, Matrix< double, _nu, 1 > >::rgba.
template<int _nu> Kinbody3dView::Kinbody3dView (const Kinbody3d< _nu > & sys, vector< Matrix4d > * xs, vector< Vectorud > * us = 0)
Create a particle view of trajectory traj
Parameters:
sys particle
xs trajectory
References gcop::SystemView< Matrix4d, Matrix< double, _nu, 1 > >::lineWidth, gcop::Kinbody3dView< _nu >::qobj, and gcop::SystemView< Matrix4d, Matrix< double, _nu, 1 > >::rgba.
template<int _nu> Kinbody3dView::~Kinbody3dView () [virtual]
Member Function Documentation
template<int _nu> void Kinbody3dView::Render (const Matrix4d * x, const Vectorud * u = 0) [virtual]
Implements gcop::SystemView< Matrix4d, Matrix< double, _nu, 1 > >.
template<int _nu> void Kinbody3dView::Render (const vector< Matrix4d > * xs, const vector< Vectorud > * us = 0, bool rs = true, int is = -1, int ie = -1, int dis = 1, int dit = 1, bool dl = false) [virtual]
Render a trajectory
Parameters:
traj trajectory
rs render state
is start index
ie end index
dis index step for rendering bodies along trajectory
dit index step for rendering states(points) along trajectory
dl always draw last state
Implements gcop::SystemView< Matrix4d, Matrix< double, _nu, 1 > >.
References gcop::Viewer::SetColor().
template<int _nu> void Kinbody3dView::Transform (const Matrix3d & R, const Vector3d & p) [static]
References gcop::SO3::Instance(), gcop::SO3::log(), and gcop::SO3::tol.
Member Data Documentation
template<int _nu = 6> double gcop::Kinbody3dView< _nu >::dirSize
Referenced by gcop::Kinbody3dView< _nu >::Kinbody3dView().
template<int _nu = 6> GLUquadricObj* gcop::Kinbody3dView< _nu >::qobj
Referenced by gcop::Kinbody3dView< _nu >::Kinbody3dView().
template<int _nu = 6> const Kinbody3d<_nu>& gcop::Kinbody3dView< _nu >::sys
The documentation for this class was generated from the following file:
lib/views/kinbody3dview.h