GCOP: gcop::AirmManifold Class Reference
gcop::AirmManifold Class Reference
#include <airmmanifold.h>
Public Member Functions
void Lift (Vector16d &v, const AirmState &xa, const AirmState &xb)
void Retract (AirmState &xb, const AirmState &xa, const Vector16d &v)
Static Public Member Functions
static AirmManifold & Instance ()
Member Function Documentation
AirmManifold & AirmManifold::Instance () [static]
void AirmManifold::Lift (Vector16d & v, const AirmState & xa, const AirmState & xb)
References gcop::SO3::cayinv(), and gcop::SO3::Instance().
void AirmManifold::Retract (AirmState & xb, const AirmState & xa, const Vector16d & v)
References gcop::SO3::cay(), and gcop::SO3::Instance().
The documentation for this class was generated from the following files:
lib/systems/manifolds/airmmanifold.h
lib/systems/manifolds/airmmanifold.cc