GCOP: gcop::Geom3dView Class Reference
gcop::Geom3dView Class Reference
#include <geom3dview.h>
Public Member Functions
Geom3dView (const char *name=0, Matrix4d *g=0)
virtual ~Geom3dView ()
virtual void RenderGeom ()=0
virtual bool RenderFrame (int i=0)
void SetColor (const double rgba[4])
Static Public Member Functions
static void Transform (const Matrix4d &g)
Public Attributes
Matrix4d * g
global pose (optional)
Matrix4d g0
origin (set to Id by default)
double rgba [4]
color
Detailed Description
Discrete Dynamical geom3d view.
Constructor & Destructor Documentation
Geom3dView::Geom3dView (const char * name = 0, Matrix4d * g = 0)
Create a view for a single state s
Parameters:
name name
s rigid body state
References rgba.
Geom3dView::~Geom3dView () [virtual]
Member Function Documentation
bool Geom3dView::RenderFrame (int i = 0) [virtual]
Render a view: all subclasses should provide this method
Parameters:
i frame #
Returns:
return true if more frames should be rendered
Reimplemented from gcop::View.
References g, g0, RenderGeom(), rgba, SetColor(), and Transform().
virtual void gcop::Geom3dView::RenderGeom () [pure virtual]
Implemented in gcop::HrotorGeom3dView, gcop::BoxView, and gcop::CylinderView.
Referenced by RenderFrame().
void Geom3dView::SetColor (const double rgba[4])
Set the rgb color of the trajectory
Parameters:
rgb rgb vector
Referenced by RenderFrame(), and gcop::HrotorGeom3dView::RenderGeom().
void Geom3dView::Transform (const Matrix4d & g) [static]
References g, gcop::SO3::Instance(), and gcop::SO3::log().
Referenced by gcop::MbsView::Render(), and RenderFrame().
Member Data Documentation
Matrix4d* gcop::Geom3dView::g
global pose (optional)
Referenced by RenderFrame(), and Transform().
Matrix4d gcop::Geom3dView::g0
origin (set to Id by default)
Referenced by RenderFrame().
double gcop::Geom3dView::rgba[4]
color
Referenced by Geom3dView(), and RenderFrame().
The documentation for this class was generated from the following files:
lib/views/geom3dview.h
lib/views/geom3dview.cc