GCOP: gcop::UuvView< c > Class Template Reference
gcop::UuvView< c > Class Template Reference
#include <uuvview.h>
Public Member Functions
UuvView (const Uuv< c > &sys)
UuvView (const Uuv< c > &sys, vector< UuvState > *xs, vector< Vectorcd > *us=0)
virtual ~UuvView ()
virtual void Render (const UuvState *x, const Vectorcd *u=0)
void Render (const vector< UuvState > *xs, const vector< Vectorcd > *us=0, bool rs=true, int is=-1, int ie=-1, int dis=1, int dit=1, bool dl=false)
Static Public Member Functions
static void Transform (const Matrix4d &g)
Public Attributes
const Uuv< c > & sys
GLUquadricObj * qobj
double dirSize
template<int c = 6>
class gcop::UuvView< c >
Constructor & Destructor Documentation
template<int c> UuvView::UuvView (const Uuv< c > & sys)
Create a particle view of trajectory traj
Parameters:
sys particle
References gcop::UuvView< c >::dirSize, gcop::SystemView< UuvState, Matrix< double, c, 1 > >::lineWidth, gcop::UuvView< c >::qobj, and gcop::SystemView< UuvState, Matrix< double, c, 1 > >::rgba.
template<int c> UuvView::UuvView (const Uuv< c > & sys, vector< UuvState > * xs, vector< Vectorcd > * us = 0)
Create a particle view of trajectory traj
Parameters:
sys particle
xs trajectory
References gcop::SystemView< UuvState, Matrix< double, c, 1 > >::lineWidth, gcop::UuvView< c >::qobj, and gcop::SystemView< UuvState, Matrix< double, c, 1 > >::rgba.
template<int c> UuvView::~UuvView () [virtual]
Member Function Documentation
template<int c> void UuvView::Render (const UuvState * x, const Vectorcd * u = 0) [virtual]
Implements gcop::SystemView< UuvState, Matrix< double, c, 1 > >.
References gcop::UuvState::g.
template<int c> void UuvView::Render (const vector< UuvState > * xs, const vector< Vectorcd > * us = 0, bool rs = true, int is = -1, int ie = -1, int dis = 1, int dit = 1, bool dl = false) [virtual]
Render a trajectory
Parameters:
traj trajectory
rs render state
is start index
ie end index
dis index step for rendering bodies along trajectory
dit index step for rendering states(points) along trajectory
dl always draw last state
Implements gcop::SystemView< UuvState, Matrix< double, c, 1 > >.
References gcop::UuvState::g, and gcop::Viewer::SetColor().
template<int c> void UuvView::Transform (const Matrix4d & g) [static]
References gcop::SO3::Instance(), gcop::SO3::log(), and gcop::SO3::tol.
Member Data Documentation
template<int c = 6> double gcop::UuvView< c >::dirSize
Referenced by gcop::UuvView< c >::UuvView().
template<int c = 6> GLUquadricObj* gcop::UuvView< c >::qobj
Referenced by gcop::UuvView< c >::UuvView().
template<int c = 6> const Uuv<c>& gcop::UuvView< c >::sys
The documentation for this class was generated from the following file:
lib/views/uuvview.h