GCOP: gcop::KinbodyProjTrack< _nu > Class Template Reference
gcop::KinbodyProjTrack< _nu > Class Template Reference
#include <kinbodyprojtrack.h>
Public Types
typedef Matrix< double, _nu, 1 > Vectorud
typedef Matrix< double, 6, _nu > Matrix6ud
typedef Matrix< double, 6, 6 > Matrix6d
Public Member Functions
KinbodyProjTrack (Kinbody3d< _nu > &sys, int nf, double vd0, double t0, double tf, double r=25, bool extforce=false, bool forces=false)
virtual void Get (Matrix4d &x, double vd, double t) const
virtual void MakeTrue ()
virtual void Add (const Vectorud &u, const Matrix4d &x, double h)
virtual void Add2 (const Vectorud &u, const Matrix4d &x, double h)
Detailed Description
template<int _nu = 6>
class gcop::KinbodyProjTrack< _nu >
Pose-track in 2D. This is the simplese possible definition assuming point (unprojected) features e.g. from stereo/laser scans with uniform spherical covariance. The framework can be easily extended to any general 2d/3d non-uniform or projected features as well.
Member Typedef Documentation
template<int _nu = 6> typedef Matrix<double, 6, 6> gcop::KinbodyProjTrack< _nu >::Matrix6d
template<int _nu = 6> typedef Matrix<double, 6, _nu> gcop::KinbodyProjTrack< _nu >::Matrix6ud
template<int _nu = 6> typedef Matrix<double, _nu, 1> gcop::KinbodyProjTrack< _nu >::Vectorud
Reimplemented from gcop::Kinbody3dTrack< _nu >.
Constructor & Destructor Documentation
template<int _nu> gcop::KinbodyProjTrack< _nu >::KinbodyProjTrack (Kinbody3d< _nu > & sys, int nf, double vd0, double t0, double tf, double r = 25, bool extforce = false, bool forces = false)
Pose graph (using simulated features around a circular track)
Parameters:
sys body3d system
nf number of features (landmarks)
t0 start time
tf end time
r radius
odometry is odometry available
extforce treat constant external force in x-y as a parameter
forces use uncertain forces in the cost function
References gcop::KinbodyProjTrack< _nu >::Get(), gcop::Kinbody3dTrack< _nu >::xos, and gcop::Kinbody3dTrack< _nu >::xs.
Member Function Documentation
template<int _nu> void gcop::KinbodyProjTrack< _nu >::Add (const Vectorud & u, const Matrix4d & x, double h) [virtual]
Reimplemented from gcop::Kinbody3dTrack< _nu >.
References gcop::random_normal().
template<int _nu> void gcop::KinbodyProjTrack< _nu >::Add2 (const Vectorud & u, const Matrix4d & x, double h) [virtual]
Add a new state/control to estimation vector
Parameters:
u commanded control
x true state (to generate measurements)
h time-step
Reimplemented from gcop::Kinbody3dTrack< _nu >.
References gcop::random_normal().
template<int _nu> void gcop::KinbodyProjTrack< _nu >::Get (Matrix4d & x, double vd, double t) const [virtual]
Reimplemented from gcop::Kinbody3dTrack< _nu >.
Referenced by gcop::KinbodyProjTrack< _nu >::KinbodyProjTrack().
template<int _nu> void gcop::KinbodyProjTrack< _nu >::MakeTrue () [virtual]
Reimplemented from gcop::Kinbody3dTrack< _nu >.
The documentation for this class was generated from the following file:
lib/systems/kinbodyprojtrack.h