GCOP: gcop::KinRccar Class Reference
gcop::KinRccar Class Reference
#include <kinrccar.h>
Public Member Functions
KinRccar ()
double Step (Matrix4d &xb, double t, const Matrix4d &xa, const Vector2d &u, double h, const VectorXd *p=0, Matrix6d *A=0, Matrix62d *B=0, Matrix< double, 6, Dynamic > *C=0)
Detailed Description
A simple kinematic car model in SE(3).
Author: Matt Sheckells mshecke1(at)jhu.edu
Constructor & Destructor Documentation
KinRccar::KinRccar ()
References gcop::Kinbody3d< 2 >::d.
Member Function Documentation
double KinRccar::Step (Matrix4d & xb, double t, const Matrix4d & xa, const Vector2d & u, double h, const VectorXd * p = 0, Matrix6d * A = 0, Matrix62d * B = 0, Matrix< double, 6, Dynamic > * C = 0)
References gcop::SE3::Ad(), gcop::SE3::cay(), gcop::Kinbody3d< 2 >::d, gcop::SE3::dcay(), and gcop::SE3::Instance().
Referenced by gcop::KinRccarPath::AddControl().
The documentation for this class was generated from the following files:
lib/systems/kinrccar.h
lib/systems/kinrccar.cc