GCOP: gcop::MbsManifold Class Reference
gcop::MbsManifold Class Reference
#include <mbsmanifold.h>
Public Member Functions
MbsManifold (int nb, bool fixed=false)
void Lift (VectorXd &v, const MbsState &xa, const MbsState &xb)
void Retract (MbsState &xb, const MbsState &xa, const VectorXd &v)
void dtau (MatrixXd &M, const VectorXd &v)
void Adtau (MatrixXd &M, const VectorXd &v)
Public Attributes
bool cay
use Cayley instead of Exponential
Constructor & Destructor Documentation
MbsManifold::MbsManifold (int nb, bool fixed = false)
Parameters:
nb number of bodies (including a base body)
fixed is the base body fixed (if fixed then it is treated as a "virtual" fixed body)
References gcop::Manifold< MbsState >::lb, and gcop::Manifold< MbsState >::ub.
Member Function Documentation
void MbsManifold::Adtau (MatrixXd & M, const VectorXd & v)
References gcop::SE3::Ad(), cay, gcop::SE3::cay(), gcop::SE3::exp(), gcop::MbsState::fixed, gcop::SE3::Instance(), and gcop::Manifold< MbsState >::lb.
void MbsManifold::dtau (MatrixXd & M, const VectorXd & v)
References cay, gcop::SE3::dcay(), gcop::MbsState::fixed, gcop::SE3::Instance(), gcop::Manifold< MbsState >::lb, and gcop::SE3::tln().
void MbsManifold::Lift (VectorXd & v, const MbsState & xa, const MbsState & xb)
References cay, gcop::Group< n, m >::cayinv(), gcop::MbsState::dr, gcop::MbsState::fixed, gcop::MbsState::gs, gcop::SE3::Instance(), gcop::SE3::inv(), gcop::SE3::log(), gcop::MbsState::r, and gcop::MbsState::vs.
void MbsManifold::Retract (MbsState & xb, const MbsState & xa, const VectorXd & v)
References cay, gcop::SE3::cay(), gcop::MbsState::dr, gcop::SE3::exp(), gcop::MbsState::fixed, gcop::MbsState::gs, gcop::SE3::Instance(), gcop::MbsState::r, and gcop::MbsState::vs.
Member Data Documentation
bool gcop::MbsManifold::cay
use Cayley instead of Exponential
Referenced by Adtau(), dtau(), Lift(), and Retract().
The documentation for this class was generated from the following files:
lib/systems/manifolds/mbsmanifold.h
lib/systems/manifolds/mbsmanifold.cc