GCOP: gcop::GunicycleManifold Class Reference
gcop::GunicycleManifold Class Reference
#include <gunicyclemanifold.h>
Public Member Functions
void Lift (Vector5d &dx, const M3V2d &xa, const M3V2d &xb)
void Retract (M3V2d &xb, const M3V2d &xa, const Vector5d &dx)
void dtau (Matrix5d &M, const Vector5d &v)
void Adtau (Matrix5d &M, const Vector5d &v)
Static Public Member Functions
static GunicycleManifold & Instance ()
Member Function Documentation
void GunicycleManifold::Adtau (Matrix5d & M, const Vector5d & v)
void GunicycleManifold::dtau (Matrix5d & M, const Vector5d & v)
GunicycleManifold & GunicycleManifold::Instance () [static]
void GunicycleManifold::Lift (Vector5d & dx, const M3V2d & xa, const M3V2d & xb)
References gcop::Group< n, m >::diff(), gcop::SE2::g2q(), and gcop::SE2::Instance().
void GunicycleManifold::Retract (M3V2d & xb, const M3V2d & xa, const Vector5d & dx)
References gcop::SE2::Instance(), and gcop::SE2::q2g().
The documentation for this class was generated from the following files:
lib/systems/manifolds/gunicyclemanifold.h
lib/systems/manifolds/gunicyclemanifold.cc