GCOP: gcop::Body2d< c > Class Template Reference
gcop::Body2d< c > Class Template Reference
#include <body2d.h>
Public Types
typedef Matrix< double, c, 1 > Vectorcd
typedef Matrix< double, 6, c > Matrix6cd
typedef Matrix< double, 3, c > Matrix3cd
Public Member Functions
Body2d (Body2dForce< c > *f=0)
double Step (Body2dState &xb, double t, const Body2dState &xa, const Vectorcd &u, double h, const VectorXd *p=0, Matrix6d *A=0, Matrix6cd *B=0, Matrix< double, 6, Dynamic > *C=0)
Public Attributes
Vector2d d
body dimensions
Vector3d I
inertia components
Body2dForce< c > * force
force from controls and external disturbances
Detailed Description
template<int c = 3>
class gcop::Body2d< c >
A "geometric" planar rigid body system. The control system is implemented as an evolution on SE(2) as opposed to a vector space.
The state is where is the pose, and is the velocity
Author: Marin Kobilarov marin(at)jhu.edu
Member Typedef Documentation
template<int c = 3> typedef Matrix<double, 3, c> gcop::Body2d< c >::Matrix3cd
template<int c = 3> typedef Matrix<double, 6, c> gcop::Body2d< c >::Matrix6cd
template<int c = 3> typedef Matrix<double, c, 1> gcop::Body2d< c >::Vectorcd
Reimplemented from gcop::System< Body2dState, 6, c >.
Constructor & Destructor Documentation
template<int c> gcop::Body2d< c >::Body2d (Body2dForce< c > * f = 0)
Member Function Documentation
template<int c> double gcop::Body2d< c >::Step (Body2dState & xb, double t, const Body2dState & xa, const Vectorcd & u, double h, const VectorXd * p = 0, Matrix6d * A = 0, Matrix6cd * B = 0, Matrix< double, 6, Dynamic > * C = 0)
References gcop::SE2::Ad(), gcop::SE2::cay(), gcop::SE2::dcay(), gcop::Body2d< c >::force, gcop::Body2d< c >::I, and gcop::SE2::Instance().
Referenced by gcop::Body2dTrack::Add(), gcop::Body2dTrack::Add2(), and gcop::Body2dGraph::Synthesize3().
Member Data Documentation
template<int c = 3> Vector2d gcop::Body2d< c >::d
body dimensions
template<int c = 3> Body2dForce<c>* gcop::Body2d< c >::force
force from controls and external disturbances
Referenced by gcop::Body2d< c >::Step(), gcop::Body2dGraph::Synthesize2(), and gcop::Body2dGraph::Synthesize3().
template<int c = 3> Vector3d gcop::Body2d< c >::I
inertia components
Referenced by gcop::Body2d< c >::Step(), and gcop::Body2dGraph::Synthesize3().
The documentation for this class was generated from the following files:
lib/systems/body2d.h
lib/systems/body2d.cc