GCOP: gcop::Body2dCost< c > Class Template Reference
gcop::Body2dCost< c > Class Template Reference
#include <body2dcost.h>
Public Types
typedef Matrix< double, c, 1 > Vectorcd
typedef Matrix< double, 6, c > Matrix6cd
typedef Matrix< double, 3, c > Matrix3cd
typedef Matrix< double, c, c > Matrixcd
Public Member Functions
Body2dCost (Body2d< c > &sys, double tf, const Body2dState &xf)
double L (double t, const Body2dState &x, const Vectorcd &u, double h, Vector6d *Lx=0, Matrix6d *Lxx=0, Vectorcd *Lu=0, Matrixcd *Luu=0, Matrix6cd *Lxu=0)
Public Attributes
Body2dTrack * track
double ko
obstacle avoidance gain
template<int c = 3>
class gcop::Body2dCost< c >
Member Typedef Documentation
template<int c = 3> typedef Matrix<double, 3, c> gcop::Body2dCost< c >::Matrix3cd
template<int c = 3> typedef Matrix<double, 6, c> gcop::Body2dCost< c >::Matrix6cd
template<int c = 3> typedef Matrix<double, c, c> gcop::Body2dCost< c >::Matrixcd
Reimplemented from gcop::LqCost< Body2dState, 6, c, Dynamic, 9 >.
template<int c = 3> typedef Matrix<double, c, 1> gcop::Body2dCost< c >::Vectorcd
Reimplemented from gcop::LqCost< Body2dState, 6, c, Dynamic, 9 >.
Constructor & Destructor Documentation
template<int c> gcop::Body2dCost< c >::Body2dCost (Body2d< c > & sys, double tf, const Body2dState & xf)
References gcop::LqCost< Body2dState, 6, c, Dynamic, 9 >::Q, gcop::LqCost< Body2dState, 6, c, Dynamic, 9 >::Qf, and gcop::LqCost< Body2dState, 6, c, Dynamic, 9 >::R.
Member Function Documentation
template<int c> double gcop::Body2dCost< c >::L (double t, const Body2dState & x, const Vectorcd & u, double h, Vector6d * Lx = 0, Matrix6d * Lxx = 0, Vectorcd * Lu = 0, Matrixcd * Luu = 0, Matrix6cd * Lxu = 0)
References gcop::SE2::g2q(), gcop::SE2::Instance(), gcop::SE2::inv(), gcop::Body2dCost< c >::ko, gcop::Body2dTrack::ls, gcop::LqCost< Body2dState, 6, c, Dynamic, 9 >::Q, gcop::LqCost< Body2dState, 6, c, Dynamic, 9 >::Qf, gcop::LqCost< Body2dState, 6, c, Dynamic, 9 >::R, gcop::Cost< Body2dState, _nx, _nu, _np, Body2dState >::tf, gcop::SE2::Tg(), gcop::Body2dCost< c >::track, gcop::Body2dTrack::w, and gcop::LqCost< Body2dState, 6, c, Dynamic, 9 >::xf.
Member Data Documentation
template<int c = 3> double gcop::Body2dCost< c >::ko
obstacle avoidance gain
Referenced by gcop::Body2dCost< c >::L().
template<int c = 3> Body2dTrack* gcop::Body2dCost< c >::track
Referenced by gcop::Body2dCost< c >::L().
The documentation for this class was generated from the following files:
lib/systems/costs/body2dcost.h
lib/systems/costs/body2dcost.cc