GCOP: gcop::Kinbody3d< _nu > Class Template Reference
gcop::Kinbody3d< _nu > Class Template Reference
#include <kinbody3d.h>
Public Types
typedef Matrix< double, _nu, 1 > Vectorud
typedef Matrix< double, 6, _nu > Matrix6ud
typedef Matrix< double, 6, 6 > Matrix6d
Public Member Functions
Kinbody3d ()
virtual double Step (Matrix4d &xb, double t, const Matrix4d &xa, const Vectorud &u, double h, const VectorXd *p=0, Matrix6d *A=0, Matrix6ud *B=0, Matrix< double, 6, Dynamic > *C=0)
Public Attributes
Vector3d d
body dimensions
Matrix6ud Bu
Detailed Description
template<int _nu = 6>
class gcop::Kinbody3d< _nu >
A simple kinematic control system modeled as a rigid body in 3d. It is meant for parameter estimation problems since there is no dynamics.
Author: Matt Sheckells mshecke1(at)jhu.edu
Member Typedef Documentation
template<int _nu = 6> typedef Matrix<double, 6, 6> gcop::Kinbody3d< _nu >::Matrix6d
template<int _nu = 6> typedef Matrix<double, 6, _nu> gcop::Kinbody3d< _nu >::Matrix6ud
template<int _nu = 6> typedef Matrix<double, _nu, 1> gcop::Kinbody3d< _nu >::Vectorud
Constructor & Destructor Documentation
template<int _nu> gcop::Kinbody3d< _nu >::Kinbody3d ()
Member Function Documentation
template<int _nu> double gcop::Kinbody3d< _nu >::Step (Matrix4d & xb, double t, const Matrix4d & xa, const Vectorud & u, double h, const VectorXd * p = 0, Matrix6d * A = 0, Matrix6ud * B = 0, Matrix< double, 6, Dynamic > * C = 0) [virtual]
References gcop::SE3::Ad(), gcop::SE3::cay(), gcop::SE3::dcay(), and gcop::SE3::Instance().
Member Data Documentation
template<int _nu = 6> Matrix6ud gcop::Kinbody3d< _nu >::Bu
template<int _nu = 6> Vector3d gcop::Kinbody3d< _nu >::d
body dimensions
Referenced by gcop::KinRccarPathCost::L().
The documentation for this class was generated from the following file:
lib/systems/kinbody3d.h