GCOP: gcop::Params Class Reference
gcop::Params Class Reference
#include <params.h>
Classes
struct RemoveDelimiter
Public Member Functions
Params ()
Params (FILE *file)
Params (const char *fileName)
Params (std::iostream &io)
virtual ~Params ()
void Load (const char *fileName)
void Load (FILE *file)
void Load (std::iostream &io)
void Save (const char *fileName) const
void Save (FILE *file) const
void Save (std::iostream &io) const
bool Exists (const char *name) const
void SetInt (const char *name, int v)
bool GetInt (const char *name, int &v) const
void SetFloat (const char *name, float v)
bool GetFloat (const char *name, float &v) const
void SetDouble (const char *name, double v)
bool GetDouble (const char *name, double &v) const
void SetVectorXd (const char *name, const VectorXd &v)
bool GetVectorXd (const char *name, VectorXd &v) const
void SetVector2d (const char *name, const Vector2d &v)
bool GetVector2d (const char *name, Vector2d &v) const
void SetVector3d (const char *name, const Vector3d &v)
bool GetVector3d (const char *name, Vector3d &v) const
void SetVector4d (const char *name, const Vector4d &v)
bool GetVector4d (const char *name, Vector4d &v) const
void SetVector5d (const char *name, const Vector5d &v)
bool GetVector5d (const char *name, Vector5d &v) const
void SetVector6d (const char *name, const Vector6d &v)
bool GetVector6d (const char *name, Vector6d &v) const
void SetMatrix3d (const char *name, const Matrix3d &m)
bool GetMatrix3d (const char *name, Matrix3d &m) const
void SetMatrix6d (const char *name, const Matrix6d &m)
bool GetMatrix6d (const char *name, Matrix6d &m) const
void SetDoubleVec (const char *name, const std::vector< double > &v)
bool GetDoubleVec (const char *name, std::vector< double > &v) const
void SetFloatArray (const char *name, int n, const float *v)
bool GetFloatArray (const char *name, int n, float *v) const
void SetDoubleArray (const char *name, int n, const double *v)
bool GetDoubleArray (const char *name, int n, double *v) const
void SetString (const char *name, const std::string &v)
bool GetString (const char *name, std::string &v) const
void SetBool (const char *name, bool v)
bool GetBool (const char *name, bool &v) const
void SetChar (const char *name, char v)
char GetChar (const char *name, char &v) const
void Print (FILE *file=stdout) const
void Print (std::iostream &io) const
Protected Member Functions
void Parse (char *line)
Protected Attributes
std::map< std::string,
std::string > valueMap
char buf [GCOP_PARAMS_MBL]
Constructor & Destructor Documentation
Params::Params ()
Params::Params (FILE * file)
Params::Params (const char * fileName)
gcop::Params::Params (std::iostream & io)
Params::~Params () [virtual]
Member Function Documentation
bool gcop::Params::Exists (const char * name) const [inline]
bool Params::GetBool (const char * name, bool & v) const
char Params::GetChar (const char * name, char & v) const
bool Params::GetDouble (const char * name, double & v) const
References replace().
bool Params::GetDoubleArray (const char * name, int n, double * v) const
References replace(), and Tokenize().
bool Params::GetDoubleVec (const char * name, std::vector< double > & v) const
References replace(), and Tokenize().
bool Params::GetFloat (const char * name, float & v) const
References replace().
bool Params::GetFloatArray (const char * name, int n, float * v) const
References replace(), and Tokenize().
bool Params::GetInt (const char * name, int & v) const
bool gcop::Params::GetMatrix3d (const char * name, Matrix3d & m) const
bool Params::GetMatrix6d (const char * name, Matrix6d & m) const
References replace(), and Tokenize().
bool Params::GetString (const char * name, std::string & v) const
bool Params::GetVector2d (const char * name, Vector2d & v) const
References replace(), and Tokenize().
bool Params::GetVector3d (const char * name, Vector3d & v) const
References replace(), and Tokenize().
bool Params::GetVector4d (const char * name, Vector4d & v) const
References replace(), and Tokenize().
bool Params::GetVector5d (const char * name, Vector5d & v) const
References replace(), and Tokenize().
bool Params::GetVector6d (const char * name, Vector6d & v) const
References replace(), and Tokenize().
bool Params::GetVectorXd (const char * name, VectorXd & v) const
References replace(), and Tokenize().
void Params::Load (const char * fileName)
void Params::Load (FILE * file)
void gcop::Params::Load (std::iostream & io)
void Params::Parse (char * line) [protected]
void Params::Print (FILE * file = stdout) const
void gcop::Params::Print (std::iostream & io) const
void Params::Save (const char * fileName) const
void Params::Save (FILE * file) const
void gcop::Params::Save (std::iostream & io) const
void Params::SetBool (const char * name, bool v)
References GCOP_PARAMS_MBL.
void Params::SetChar (const char * name, char v)
References GCOP_PARAMS_MBL.
void Params::SetDouble (const char * name, double v)
References GCOP_PARAMS_MBL.
void Params::SetDoubleArray (const char * name, int n, const double * v)
void Params::SetDoubleVec (const char * name, const std::vector< double > & v)
void Params::SetFloat (const char * name, float v)
References GCOP_PARAMS_MBL.
void Params::SetFloatArray (const char * name, int n, const float * v)
void Params::SetInt (const char * name, int v)
References GCOP_PARAMS_MBL.
void gcop::Params::SetMatrix3d (const char * name, const Matrix3d & m)
void Params::SetMatrix6d (const char * name, const Matrix6d & m)
void Params::SetString (const char * name, const std::string & v)
void Params::SetVector2d (const char * name, const Vector2d & v)
void Params::SetVector3d (const char * name, const Vector3d & v)
void Params::SetVector4d (const char * name, const Vector4d & v)
void Params::SetVector5d (const char * name, const Vector5d & v)
void Params::SetVector6d (const char * name, const Vector6d & v)
void Params::SetVectorXd (const char * name, const VectorXd & v)
Member Data Documentation
char gcop::Params::buf[GCOP_PARAMS_MBL] [protected]
std::map<std::string, std::string> gcop::Params::valueMap [protected]
The documentation for this class was generated from the following files:
lib/utils/params.h
lib/utils/params.cc