GCOP: gcop::InsManifold Class Reference
gcop::InsManifold Class Reference
#include <insmanifold.h>
Public Member Functions
void Lift (Vector15d &v, const InsState &xa, const InsState &xb)
void Retract (InsState &xb, const InsState &xa, const Vector15d &v)
void dtau (Matrix15d &M, const Vector15d &v)
void Adtau (Matrix15d &M, const Vector15d &v)
Static Public Member Functions
static InsManifold & Instance ()
Member Function Documentation
void InsManifold::Adtau (Matrix15d & M, const Vector15d & v)
References Instance().
void InsManifold::dtau (Matrix15d & M, const Vector15d & v)
References Instance().
InsManifold & InsManifold::Instance () [static]
Referenced by Adtau(), dtau(), Lift(), and Retract().
void InsManifold::Lift (Vector15d & v, const InsState & xa, const InsState & xb)
References gcop::InsState::ba, gcop::InsState::bg, Instance(), gcop::InsState::p, gcop::InsState::R, and gcop::InsState::v.
void InsManifold::Retract (InsState & xb, const InsState & xa, const Vector15d & v)
References gcop::InsState::ba, gcop::InsState::bg, Instance(), gcop::InsState::p, gcop::InsState::R, and gcop::InsState::v.
The documentation for this class was generated from the following files:
lib/systems/manifolds/insmanifold.h
lib/systems/manifolds/insmanifold.cc