GCOP: gcop::Joint Class Reference
gcop::Joint Class Reference
#include <joint.h>
Public Member Functions
Joint ()
Joint (const Vector6d &a, const Matrix4d &gp, const Matrix4d &gc, double damping=0, double friction=0)
virtual ~Joint ()
void Init ()
Public Attributes
Vector6d a
axis
Matrix4d gp
fixed xform from parent to joint
Matrix4d gc
fixed xfom from child to joint
double damping
damping terms: Ns/m for trans or Nm s/rad for rev
double friction
static friction: N for prismatic, Nm for rev
double lower
lower limit (for revolute or prismatic joints)
double upper
upper limit (for revolute or prismatic joints)
Matrix6d Ac
change of frame Ad(gc)
Matrix4d gpi
from parent to joint inverse
Matrix4d gci
from child to joint inverse
Vector6d S
Jacobian S=Ac*a.
string name
Unique name of the joint.
Constructor & Destructor Documentation
Joint::Joint ()
References Init().
Joint::Joint (const Vector6d & a, const Matrix4d & gp, const Matrix4d & gc, double damping = 0, double friction = 0)
References Init().
Joint::~Joint () [virtual]
Member Function Documentation
void Joint::Init ()
References a, Ac, gcop::SE3::Ad(), gc, gci, gp, gpi, gcop::SE3::Instance(), gcop::SE3::inv(), and S.
Referenced by gcop::Mbs::Init(), and Joint().
Member Data Documentation
Vector6d gcop::Joint::a
axis
Referenced by Init(), and gcop::Mbs::KStep().
Matrix6d gcop::Joint::Ac
change of frame Ad(gc)
Referenced by Init().
double gcop::Joint::damping
damping terms: Ns/m for trans or Nm s/rad for rev
double gcop::Joint::friction
static friction: N for prismatic, Nm for rev
Matrix4d gcop::Joint::gc
fixed xfom from child to joint
Referenced by Init().
Matrix4d gcop::Joint::gci
from child to joint inverse
Referenced by Init(), and gcop::Mbs::KStep().
Matrix4d gcop::Joint::gp
fixed xform from parent to joint
Referenced by Init(), and gcop::Mbs::KStep().
Matrix4d gcop::Joint::gpi
from parent to joint inverse
Referenced by Init().
double gcop::Joint::lower
lower limit (for revolute or prismatic joints)
string gcop::Joint::name
Unique name of the joint.
Vector6d gcop::Joint::S
Jacobian S=Ac*a.
Referenced by Init(), and gcop::Mbs::NewtonEulerJacobian().
double gcop::Joint::upper
upper limit (for revolute or prismatic joints)
The documentation for this class was generated from the following files:
lib/systems/joint.h
lib/systems/joint.cc