GCOP: gcop_urdf::Pose Class Reference
gcop_urdf::Pose Class Reference
#include <pose.h>
Public Member Functions
Pose ()
void clear ()
bool initXml (TiXmlElement *xml)
Pose GetInverse () const
Pose operator* (const Pose &p2) const
Public Attributes
Vector3 position
Rotation rotation
Friends
std::ostream & operator<< (std::ostream &out, const Pose &vec)
Constructor & Destructor Documentation
gcop_urdf::Pose::Pose () [inline]
Member Function Documentation
void gcop_urdf::Pose::clear () [inline]
References gcop_urdf::Vector3::clear(), gcop_urdf::Rotation::clear(), position, and rotation.
Referenced by gcop_urdf::bulletmbsgenerator(), gcop_urdf::Inertial::clear(), gcop_urdf::Visual::clear(), gcop_urdf::Collision::clear(), gcop_urdf::Joint::clear(), and initXml().
Pose gcop_urdf::Pose::GetInverse () const [inline]
References gcop_urdf::Rotation::GetInverse(), position, and rotation.
bool gcop_urdf::Pose::initXml (TiXmlElement * xml) [inline]
References gcop_urdf::Vector3::clear(), gcop_urdf::Rotation::clear(), clear(), gcop_urdf::Vector3::init(), gcop_urdf::Rotation::init(), position, and rotation.
Pose gcop_urdf::Pose::operator* (const Pose & p2) const [inline]
References position, and rotation.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Pose & vec) [friend]
Member Data Documentation
Vector3 gcop_urdf::Pose::position
Referenced by clear(), GetInverse(), initXml(), and operator*().
Rotation gcop_urdf::Pose::rotation
Referenced by clear(), GetInverse(), initXml(), and operator*().
The documentation for this class was generated from the following file:
lib/utils/pose.h