GCOP: gcop::GunicycleCost Class Reference
gcop::GunicycleCost Class Reference
#include <gunicyclecost.h>
Public Member Functions
GunicycleCost (Gunicycle &sys, double tf, const M3V2d &xf)
double L (double t, const M3V2d &x, const Vector2d &u, double h, Vector5d *Lx=0, Matrix5d *Lxx=0, Vector2d *Lu=0, Matrix2d *Luu=0, Matrix52d *Lxu=0)
Constructor & Destructor Documentation
GunicycleCost::GunicycleCost (Gunicycle & sys, double tf, const M3V2d & xf)
References gcop::LqCost< M3V2d, 5, 2, Dynamic, 7 >::Q, gcop::LqCost< M3V2d, 5, 2, Dynamic, 7 >::Qf, and gcop::LqCost< M3V2d, 5, 2, Dynamic, 7 >::R.
Member Function Documentation
double GunicycleCost::L (double t, const M3V2d & x, const Vector2d & u, double h, Vector5d * Lx = 0, Matrix5d * Lxx = 0, Vector2d * Lu = 0, Matrix2d * Luu = 0, Matrix52d * Lxu = 0)
References gcop::SE2::g2q(), gcop::SE2::Instance(), gcop::LqCost< M3V2d, 5, 2, Dynamic, 7 >::Q, gcop::LqCost< M3V2d, 5, 2, Dynamic, 7 >::Qf, gcop::LqCost< M3V2d, 5, 2, Dynamic, 7 >::R, gcop::Cost< M3V2d, _nx, _nu, _np, M3V2d >::tf, and gcop::SE2::Tg().
The documentation for this class was generated from the following files:
lib/systems/costs/gunicyclecost.h
lib/systems/costs/gunicyclecost.cc