GCOP: gcop::SE2 Class Reference
gcop::SE2 Class Reference
#include <se2.h>
Public Member Functions
SE2 ()
void inv (Matrix3d &mi, const Matrix3d &m) const
void hat (Matrix3d &vh, const Vector3d &v) const
void hatinv (Vector3d &v, const Matrix3d &vh) const
void Tg (Matrix3d &m, const Matrix3d &g) const
void Ad (Matrix3d &m, const Matrix3d &g) const
void ad (Matrix3d &m, const Vector3d &v) const
void adinv (Vector3d &v, const Matrix3d &m) const
void exp (Matrix3d &m, const Vector3d &v) const
void log (Vector3d &v, const Matrix3d &m) const
void plog (Vector3d &v, const Matrix3d &m) const
void cay (Matrix3d &g, const Vector3d &v) const
void cayinv (Vector3d &v, const Matrix3d &m) const
void dcay (Matrix3d &m, const Vector3d &v) const
void dcayinv (Matrix3d &m, const Vector3d &v) const
void q2g (Matrix3d &g, const Vector3d &q) const
void g2q (Vector3d &q, const Matrix3d &g) const
Static Public Member Functions
static SE2 & Instance ()
static RowVector2d r2hat (const Vector2d &a)
static double cross2 (Vector2d a, Vector2d b)
Public Attributes
double tol
numerical tolerance
Constructor & Destructor Documentation
SE2::SE2 ()
Member Function Documentation
void SE2::Ad (Matrix3d & m, const Matrix3d & g) const
Referenced by gcop::Kinbody2d::Step(), gcop::Gunicycle::Step(), and gcop::Body2d::Step().
void SE2::ad (Matrix3d & m, const Vector3d & v) const
void SE2::adinv (Vector3d & v, const Matrix3d & m) const
void SE2::cay (Matrix3d & g, const Vector3d & v) const
Referenced by gcop::Kinbody2d::Step(), gcop::Gunicycle::Step(), gcop::Body2d::Step(), gcop::Posegraph2d::Synthesize(), gcop::Body2dGraph::Synthesize(), gcop::Posegraph2d::Synthesize2(), gcop::Body2dGraph::Synthesize2(), and gcop::Body2dGraph::Synthesize3().
void SE2::cayinv (Vector3d & v, const Matrix3d & m) const
References tol.
static double gcop::SE2::cross2 (Vector2d a, Vector2d b) [inline, static]
void SE2::dcay (Matrix3d & m, const Vector3d & v) const
Referenced by gcop::Kinbody2d::Step(), gcop::Gunicycle::Step(), and gcop::Body2d::Step().
void SE2::dcayinv (Matrix3d & m, const Vector3d & v) const
void SE2::exp (Matrix3d & m, const Vector3d & v) const
References tol.
void SE2::g2q (Vector3d & q, const Matrix3d & g) const
Referenced by gcop::GunicycleCost::L(), gcop::Body2dCost::L(), gcop::GunicycleManifold::Lift(), gcop::AirplaneView::Render(), gcop::GunicycleView::Render(), gcop::Kinbody2dView::Render(), and gcop::Body2dView::Render().
void SE2::hat (Matrix3d & vh, const Vector3d & v) const
void SE2::hatinv (Vector3d & v, const Matrix3d & vh) const
SE2 & SE2::Instance () [static]
Referenced by gcop::Body2dTrack::Get(), gcop::GunicycleCost::L(), gcop::Body2dCost::L(), gcop::GunicycleManifold::Lift(), gcop::GunicycleView::Render(), gcop::AirplaneView::Render(), gcop::Kinbody2dView::Render(), gcop::Body2dView::Render(), gcop::GunicycleManifold::Retract(), gcop::Kinbody2d::Step(), gcop::Gunicycle::Step(), gcop::Body2d::Step(), gcop::Posegraph2d::Synthesize(), gcop::Body2dGraph::Synthesize(), gcop::Posegraph2d::Synthesize2(), gcop::Body2dGraph::Synthesize2(), and gcop::Body2dGraph::Synthesize3().
void SE2::inv (Matrix3d & mi, const Matrix3d & m) const
Referenced by gcop::Body2dCost::L().
void SE2::log (Vector3d & v, const Matrix3d & m) const
References tol.
void SE2::plog (Vector3d & v, const Matrix3d & m) const
void SE2::q2g (Matrix3d & g, const Vector3d & q) const
Referenced by gcop::Body2dTrack::Get(), and gcop::GunicycleManifold::Retract().
static RowVector2d gcop::SE2::r2hat (const Vector2d & a) [inline, static]
void SE2::Tg (Matrix3d & m, const Matrix3d & g) const
Referenced by gcop::GunicycleCost::L(), and gcop::Body2dCost::L().
Member Data Documentation
double gcop::SE2::tol
numerical tolerance
Referenced by cayinv(), exp(), and log().
The documentation for this class was generated from the following files:
lib/utils/se2.h
lib/utils/se2.cc