GCOP: gcop::SE3 Class Reference
gcop::SE3 Class Reference
#include <se3.h>
Public Member Functions
SE3 ()
void inv (Matrix4d &gi, const Matrix4d &g) const
void hat (Matrix4d &vh, const Vector6d &v) const
void hatinv (Vector6d &v, const Matrix4d &vh) const
void Tg (Matrix6d &M, const Matrix4d &g) const
void Ad (Matrix6d &M, const Matrix4d &g) const
void ad (Matrix6d &M, const Vector6d &v) const
void adt (Matrix6d &M, const Vector6d &mu) const
void adinv (Vector6d &v, const Matrix6d &m) const
void exp (Matrix4d &g, const Vector6d &v) const
void log (Vector6d &v, const Matrix4d &g) const
void cay (Matrix4d &g, const Vector6d &v) const
void dcay (Matrix6d &M, const Vector6d &v) const
void dcayinv (Matrix6d &M, const Vector6d &v) const
void tlnmu (Vector6d &mup, const Vector6d &v, const Vector6d &mu) const
void tln (Matrix6d &M, const Vector6d &v) const
void q2g (Matrix4d &g, const Vector6d &q) const
void quatxyz2g (Matrix4d &g, const Vector7d &wquatxyz) const
void g2quatxyz (Vector7d &wquatxyz, const Matrix4d &g) const
void g2q (Vector6d &q, const Matrix4d &g) const
void rpyxyz2g (Matrix4d &g, const Vector3d &rpy, const Vector3d &xyz) const
void g2rpyxyz (Vector3d &rpy, Vector3d &xyz, const Matrix4d &g) const
Static Public Member Functions
static SE3 & Instance ()
Public Attributes
double tol
numerical tolerance
SO3 & so3
convenience object for accessing SO3 operations
Constructor & Destructor Documentation
SE3::SE3 ()
Member Function Documentation
void SE3::Ad (Matrix6d & M, const Matrix4d & g) const
References gcop::SO3::ad(), and so3.
Referenced by gcop::MbsManifold::Adtau(), gcop::Mbs::Bias(), gcop::Mbs::DBias(), gcop::Joint::Init(), gcop::Mbs::Mass(), gcop::Mbs::NewtonEulerJacobian(), gcop::KinRccar::Step(), and gcop::Kinbody3d< _nu >::Step().
void SE3::ad (Matrix6d & M, const Vector6d & v) const
References gcop::SO3::ad(), and so3.
Referenced by gcop::Uuv< c >::SympStep(), and tln().
void SE3::adinv (Vector6d & v, const Matrix6d & m) const
References gcop::SO3::hatinv(), and so3.
void SE3::adt (Matrix6d & M, const Vector6d & mu) const
References gcop::SO3::ad(), and so3.
Referenced by gcop::Mbs::NewtonEulerJacobian(), and gcop::Uuv< c >::SympStep().
void SE3::cay (Matrix4d & g, const Vector6d & v) const
Referenced by gcop::MbsManifold::Adtau(), gcop::MbsCspace::Retract(), gcop::MbsManifold::Retract(), gcop::KinRccar::Step(), gcop::Kinbody3d< _nu >::Step(), and gcop::Uuv< c >::SympStep().
void SE3::dcay (Matrix6d & M, const Vector6d & v) const
References gcop::Manifold< Matrix< double, m, m >, n >::n.
Referenced by gcop::MbsManifold::dtau(), gcop::KinRccar::Step(), and gcop::Kinbody3d< _nu >::Step().
void SE3::dcayinv (Matrix6d & M, const Vector6d & v) const
References gcop::SO3::ad(), gcop::SO3::dcayinv(), gcop::Group< n, m >::Id, and so3.
void SE3::exp (Matrix4d & g, const Vector6d & v) const
References gcop::SO3::dexp(), gcop::SO3::exp(), and so3.
Referenced by gcop::MbsManifold::Adtau(), gcop::Mbs::FK(), gcop::Mbs::KStep(), gcop::Mbs::Rec(), and gcop::MbsManifold::Retract().
void SE3::g2q (Vector6d & q, const Matrix4d & g) const
References gcop::SO3::g2q(), and so3.
void SE3::g2quatxyz (Vector7d & wquatxyz, const Matrix4d & g) const
References gcop::SO3::g2quat(), and so3.
void SE3::g2rpyxyz (Vector3d & rpy, Vector3d & xyz, const Matrix4d & g) const
References gcop::SO3::g2q(), and so3.
void SE3::hat (Matrix4d & vh, const Vector6d & v) const
References gcop::SO3::ad(), and so3.
void SE3::hatinv (Vector6d & v, const Matrix4d & vh) const
References gcop::SO3::hatinv(), and so3.
SE3 & SE3::Instance () [static]
Referenced by gcop::MbsManifold::Adtau(), gcop::AirbotView::AirbotView(), gcop_urdf::bulletmbsgenerator(), gcop::MbsManifold::dtau(), gcop::Joint::Init(), gcop::MbsCspace::Lift(), gcop::MbsManifold::Lift(), gcop::MbsCspace::Retract(), gcop::MbsManifold::Retract(), gcop::MbsController::Set(), gcop::KinRccar::Step(), gcop::Kinbody3d< _nu >::Step(), and gcop::Uuv< c >::SympStep().
void SE3::inv (Matrix4d & gi, const Matrix4d & g) const
Referenced by gcop::Mbs::Bias(), gcop::Mbs::DBias(), gcop::Joint::Init(), gcop::Mbs::KStep(), gcop::MbsCspace::Lift(), gcop::MbsManifold::Lift(), gcop::Mbs::Mass(), gcop::Mbs::NewtonEulerJacobian(), gcop::Mbs::Rec(), and gcop::MbsController::Set().
void SE3::log (Vector6d & v, const Matrix4d & g) const
References gcop::SO3::dexpinv(), gcop::SO3::log(), and so3.
Referenced by gcop::Mbs::KStep(), gcop::MbsManifold::Lift(), gcop::Mbs::Rec(), and gcop::MbsController::Set().
void SE3::q2g (Matrix4d & g, const Vector6d & q) const
References gcop::SO3::q2g(), and so3.
void SE3::quatxyz2g (Matrix4d & g, const Vector7d & wquatxyz) const
References gcop::SO3::quat2g(), and so3.
Referenced by gcop_urdf::bulletmbsgenerator().
void SE3::rpyxyz2g (Matrix4d & g, const Vector3d & rpy, const Vector3d & xyz) const
References gcop::SO3::q2g(), and so3.
Referenced by gcop::Airbot::Airbot(), gcop::AirbotView::AirbotView(), gcop::Airm::Airm(), gcop::Chain::Chain(), gcop::Chain1::Chain1(), and gcop::Snake::Snake().
void SE3::Tg (Matrix6d & M, const Matrix4d & g) const
void SE3::tln (Matrix6d & M, const Vector6d & v) const
References ad().
Referenced by gcop::MbsManifold::dtau(), gcop::Mbs::NewtonEulerJacobian(), and gcop::Uuv< c >::SympStep().
void SE3::tlnmu (Vector6d & mup, const Vector6d & v, const Vector6d & mu) const
Referenced by gcop::Mbs::DBias().
Member Data Documentation
SO3& gcop::SE3::so3
convenience object for accessing SO3 operations
Referenced by Ad(), ad(), adinv(), adt(), dcayinv(), exp(), g2q(), g2quatxyz(), g2rpyxyz(), hat(), hatinv(), log(), q2g(), quatxyz2g(), and rpyxyz2g().
double gcop::SE3::tol
numerical tolerance
The documentation for this class was generated from the following files:
lib/utils/se3.h
lib/utils/se3.cc