GCOP: gcop::Posegraph2dView Class Reference
gcop::Posegraph2dView Class Reference
#include <posegraph2dview.h>
Public Member Functions
Posegraph2dView (const Posegraph2d &pg)
virtual void Render ()
virtual bool RenderFrame (int i)
Public Attributes
const Posegraph2d & pg
float rgba [4]
Detailed Description
Rigid body view. Supports rendering either a single state or a whole trajectory of states.
Constructor & Destructor Documentation
Posegraph2dView::Posegraph2dView (const Posegraph2d & pg)
Create a view for a single state s
Parameters:
name name
s rigid body state
References rgba.
Member Function Documentation
void Posegraph2dView::Render () [virtual]
Render a view: all subclasses should provide this method
Reimplemented from gcop::View.
References RenderFrame().
bool Posegraph2dView::RenderFrame (int i) [virtual]
Render a view: all subclasses should provide this method
Parameters:
i frame #
Returns:
return true if more frames should be rendered
Reimplemented from gcop::View.
References gcop::Viewer::DrawText(), gcop::Posegraph2d::gs, gcop::Posegraph2d::Js, gcop::Posegraph2d::p, pg, rgba, and gcop::Viewer::SetColor().
Referenced by Render().
Member Data Documentation
const Posegraph2d& gcop::Posegraph2dView::pg
Referenced by RenderFrame().
float gcop::Posegraph2dView::rgba[4]
Referenced by Posegraph2dView(), and RenderFrame().
The documentation for this class was generated from the following files:
lib/views/posegraph2dview.h
lib/views/posegraph2dview.cc