GCOP: gcop::Body2dGraphView Class Reference
gcop::Body2dGraphView Class Reference
#include <body2dgraphview.h>
Public Member Functions
Body2dGraphView (const Body2dGraph &pg)
virtual void Render ()
virtual bool RenderFrame (int i)
Public Attributes
const Body2dGraph & pg
float rgba [4]
bool drawLandmarks
Detailed Description
Rigid body view. Supports rendering either a single state or a whole trajectory of states.
Constructor & Destructor Documentation
Body2dGraphView::Body2dGraphView (const Body2dGraph & pg)
Create a view for a single state s
Parameters:
name name
s rigid body state
References drawLandmarks, and rgba.
Member Function Documentation
void Body2dGraphView::Render () [virtual]
Render a view: all subclasses should provide this method
Reimplemented from gcop::View.
References RenderFrame().
bool Body2dGraphView::RenderFrame (int i) [virtual]
Render a view: all subclasses should provide this method
Parameters:
i frame #
Returns:
return true if more frames should be rendered
Reimplemented from gcop::View.
References gcop::Viewer::DrawArrow(), drawLandmarks, gcop::Viewer::DrawText(), gcop::Body2dGraph::extforce, gcop::Body2dGraph::Js, gcop::Body2dGraph::p, pg, rgba, gcop::Body2dGraph::us, and gcop::Body2dGraph::xs.
Referenced by Render().
Member Data Documentation
bool gcop::Body2dGraphView::drawLandmarks
Referenced by Body2dGraphView(), and RenderFrame().
const Body2dGraph& gcop::Body2dGraphView::pg
Referenced by RenderFrame().
float gcop::Body2dGraphView::rgba[4]
Referenced by Body2dGraphView(), and RenderFrame().
The documentation for this class was generated from the following files:
lib/views/body2dgraphview.h
lib/views/body2dgraphview.cc