GCOP: gcop::Body2dSlamCost Class Reference
gcop::Body2dSlamCost Class Reference
#include <body2dslamcost.h>
Public Member Functions
Body2dSlamCost (Body2d<> &sys, double tf, const Body2dGraph &pg)
double Lp (double t, const Body2dState &x, const Vector3d &u, const VectorXd &p, Vector6d *Lx=0, Matrix6d *Lxx=0, Vector3d *Lu=0, Matrix3d *Luu=0, Matrix63d *Lxu=0, VectorXd *Lp=0, MatrixXd *Lpp=0, MatrixX6d *Lpx=0)
Public Attributes
const Body2dGraph & pg
Constructor & Destructor Documentation
Body2dSlamCost::Body2dSlamCost (Body2d<> & sys, double tf, const Body2dGraph & pg)
Member Function Documentation
double Body2dSlamCost::Lp (double t, const Body2dState & x, const Vector3d & u, const VectorXd & p, Vector6d * Lx = 0, Matrix6d * Lxx = 0, Vector3d * Lu = 0, Matrix3d * Luu = 0, Matrix63d * Lxu = 0, VectorXd * Lp = 0, MatrixXd * Lpp = 0, MatrixX6d * Lpx = 0)
References gcop::Body2dGraph::cp, cross2(), gcop::Body2dGraph::cv, gcop::Body2dGraph::cw, gcop::Body2dGraph::extforce, gcop::Body2dGraph::forces, gcop::Body2dGraph::Is, gcop::Cost< Body2dState, 6, 3 >::L(), gcop::Body2dGraph::odometry, pg, r2hat(), gcop::Cost< Body2dState, 6, 3 >::tf, gcop::Body2dGraph::us, and gcop::Body2dGraph::vs.
Member Data Documentation
const Body2dGraph& gcop::Body2dSlamCost::pg
Referenced by Lp().
The documentation for this class was generated from the following files:
lib/algos/body2dslamcost.h
lib/algos/body2dslamcost.cc