GCOP: gcop::Kinbody2d Class Reference
gcop::Kinbody2d Class Reference
#include <kinbody2d.h>
Public Member Functions
Kinbody2d ()
double Step (Matrix3d &xb, double t, const Matrix3d &xa, const Vector3d &u, double h, const VectorXd *p, Matrix3d *A=0, Matrix3d *B=0, Matrix< double, 3, Dynamic > *C=0)
Public Attributes
Vector2d d
body dimensions
Detailed Description
A simple kinematic control system modeled as a rigid body in 2d. It is meant for parameter estimation problems since there is no dynamics.
Author: Marin Kobilarov marin(at)jhu.edu
Constructor & Destructor Documentation
Kinbody2d::Kinbody2d ()
Member Function Documentation
double Kinbody2d::Step (Matrix3d & xb, double t, const Matrix3d & xa, const Vector3d & u, double h, const VectorXd * p, Matrix3d * A = 0, Matrix3d * B = 0, Matrix< double, 3, Dynamic > * C = 0)
References gcop::SE2::Ad(), gcop::SE2::cay(), gcop::SE2::dcay(), and gcop::SE2::Instance().
Member Data Documentation
Vector2d gcop::Kinbody2d::d
body dimensions
Referenced by gcop::Kinbody2dView::Render().
The documentation for this class was generated from the following files:
lib/systems/kinbody2d.h
lib/systems/kinbody2d.cc