GCOP: gcop_urdf::Vector3 Class Reference
gcop_urdf::Vector3 Class Reference
#include <pose.h>
Public Member Functions
Vector3 (double _x, double _y, double _z)
Vector3 ()
void clear ()
bool init (const std::string &vector_str)
Vector3 operator+ (Vector3 vec)
Vector3 operator- ()
Public Attributes
double x
double y
double z
Constructor & Destructor Documentation
gcop_urdf::Vector3::Vector3 (double _x, double _y, double _z) [inline]
References x, y, and z.
gcop_urdf::Vector3::Vector3 () [inline]
Referenced by operator+(), and operator-().
Member Function Documentation
void gcop_urdf::Vector3::clear () [inline]
References x, y, and z.
Referenced by gcop_urdf::Box::clear(), gcop_urdf::Joint::clear(), gcop_urdf::Pose::clear(), init(), and gcop_urdf::Pose::initXml().
bool gcop_urdf::Vector3::init (const std::string & vector_str) [inline]
References clear(), x, y, and z.
Referenced by gcop_urdf::Rotation::init(), and gcop_urdf::Pose::initXml().
Vector3 gcop_urdf::Vector3::operator+ (Vector3 vec) [inline]
References Vector3(), x, y, and z.
Vector3 gcop_urdf::Vector3::operator- () [inline]
References Vector3(), x, y, and z.
Member Data Documentation
double gcop_urdf::Vector3::x
Referenced by clear(), gcop_urdf::Mesh::clear(), init(), gcop_urdf::Rotation::init(), gcop_urdf::Rotation::operator*(), operator+(), operator-(), and Vector3().
double gcop_urdf::Vector3::y
Referenced by clear(), gcop_urdf::Mesh::clear(), init(), gcop_urdf::Rotation::init(), gcop_urdf::Rotation::operator*(), operator+(), operator-(), and Vector3().
double gcop_urdf::Vector3::z
Referenced by clear(), gcop_urdf::Mesh::clear(), init(), gcop_urdf::Rotation::init(), gcop_urdf::Rotation::operator*(), operator+(), operator-(), and Vector3().
The documentation for this class was generated from the following file:
lib/utils/pose.h