GCOP: gcop::Kinbody3dManifold Class Reference
gcop::Kinbody3dManifold Class Reference
#include <kinbody3dmanifold.h>
Public Member Functions
void Lift (Vector6d &v, const Matrix4d &xa, const Matrix4d &xb)
void Retract (Matrix4d &xb, const Matrix4d &xa, const Vector6d &v)
void dtau (Matrix4d &M, const Vector6d &v)
void Adtau (Matrix4d &M, const Vector6d &v)
Static Public Member Functions
static Kinbody3dManifold & Instance ()
Member Function Documentation
void Kinbody3dManifold::Adtau (Matrix4d & M, const Vector6d & v)
References Instance().
void Kinbody3dManifold::dtau (Matrix4d & M, const Vector6d & v)
References Instance().
Kinbody3dManifold & Kinbody3dManifold::Instance () [static]
Referenced by Adtau(), dtau(), Lift(), and Retract().
void Kinbody3dManifold::Lift (Vector6d & v, const Matrix4d & xa, const Matrix4d & xb)
References Instance().
void Kinbody3dManifold::Retract (Matrix4d & xb, const Matrix4d & xa, const Vector6d & v)
References Instance().
The documentation for this class was generated from the following files:
lib/systems/manifolds/kinbody3dmanifold.h
lib/systems/manifolds/kinbody3dmanifold.cc