GCOP: gcop::Tparam< T, nx, nu, np, _ntp, Tc > Class Template Reference
gcop::Tparam< T, nx, nu, np, _ntp, Tc > Class Template Reference
#include <tparam.h>
Public Member Functions
Tparam (System< T, nx, nu, np > &sys, int ntp=0)
virtual bool To (Vectorntpd &s, const vector< double > &ts, const vector< T > &xs, const vector< Vectorcd > &us, const Vectormd *p=0)
virtual bool From (vector< double > &ts, vector< T > &xs, vector< Vectorcd > &us, const Vectorntpd &s, Vectormd *p=0)
virtual bool SetContext (const Tc &c)
Public Attributes
System< T, nx, nu, np > & sys
system
int ntp
parameter vector dimension
Detailed Description
template<typename T, int nx = Dynamic, int nu = Dynamic, int np = Dynamic, int _ntp = Dynamic, typename Tc = T>
class gcop::Tparam< T, nx, nu, np, _ntp, Tc >
General trajectory parametrization functionality. A trajectory can be parametrizes using a set of discrete controls, a continuous control paramertization, a set of discrete states, a set of discrete flat outputs, etc...
The default implementation is the simplest: a set of discrete controls
Author: Marin Kobilarov (c) 2005--2013
Constructor & Destructor Documentation
template<typename T, int nx, int nu, int np, int _ntp, typename Tc > gcop::Tparam< T, nx, nu, np, _ntp, Tc >::Tparam (System< T, nx, nu, np > & sys, int ntp = 0)
Member Function Documentation
template<typename T, int nx, int nu, int np, int _ntp, typename Tc > bool gcop::Tparam< T, nx, nu, np, _ntp, Tc >::From (vector< double > & ts, vector< T > & xs, vector< Vectorcd > & us, const Vectorntpd & s, Vectormd * p = 0) [virtual]
Convert from trajectory (ts,xs,us,p) to parameters s
Parameters:
ts times
xs states
us controls
s trajectory parametrization vector
p system parameters (optional)
Returns:
true if conversion was successful
Reimplemented in gcop::FlatOutputTparam< T, nx, nu, np, _ntp >, gcop::ControllerTparam< Tx, nx, nu, np, _ntp, Tc >, gcop::SplineTparam< T, nx, nu, np, _ntp >, and gcop::ControlTparam< T, nx, nu, np, _ntp >.
Referenced by gcop::SystemCe< T, n, c, np, ntp, Tc >::SystemCe().
template<typename T, int nx = Dynamic, int nu = Dynamic, int np = Dynamic, int _ntp = Dynamic, typename Tc = T> virtual bool gcop::Tparam< T, nx, nu, np, _ntp, Tc >::SetContext (const Tc & c) [inline, virtual]
Referenced by gcop::SystemCe< T, n, c, np, ntp, Tc >::SystemCe().
template<typename T, int nx, int nu, int np, int _ntp, typename Tc > bool gcop::Tparam< T, nx, nu, np, _ntp, Tc >::To (Vectorntpd & s, const vector< double > & ts, const vector< T > & xs, const vector< Vectorcd > & us, const Vectormd * p = 0) [virtual]
Convert from paramer s to trajectory (ts,xs,us,p)
Parameters:
s trajectory parametrization vector
ts times
xs states
us controls
p system parameters (optional)
Returns:
true if conversion was successful
Reimplemented in gcop::FlatOutputTparam< T, nx, nu, np, _ntp >, gcop::ControllerTparam< Tx, nx, nu, np, _ntp, Tc >, gcop::SplineTparam< T, nx, nu, np, _ntp >, and gcop::ControlTparam< T, nx, nu, np, _ntp >.
Referenced by gcop::GnDocp< T, _nx, _nu, _np, _ng, _ntp >::GnDocp(), and gcop::SystemCe< T, n, c, np, ntp, Tc >::SystemCe().
Member Data Documentation
template<typename T, int nx = Dynamic, int nu = Dynamic, int np = Dynamic, int _ntp = Dynamic, typename Tc = T> int gcop::Tparam< T, nx, nu, np, _ntp, Tc >::ntp
parameter vector dimension
Referenced by gcop::GnDocp< T, _nx, _nu, _np, _ng, _ntp >::GnDocp(), and gcop::SystemCe< T, n, c, np, ntp, Tc >::SystemCe().
template<typename T, int nx = Dynamic, int nu = Dynamic, int np = Dynamic, int _ntp = Dynamic, typename Tc = T> System<T, nx, nu, np>& gcop::Tparam< T, nx, nu, np, _ntp, Tc >::sys
system
The documentation for this class was generated from the following file:
lib/systems/parametrization/tparam.h