GCOP: gcop::Uuv< c > Class Template Reference
gcop::Uuv< c > Class Template Reference
#include <uuv.h>
Public Member Functions
Uuv ()
virtual ~Uuv ()
double Step (UuvState &xb, double t, const UuvState &xa, const Vectorcd &u, double h, const VectorXd *p=0, Matrix12d *A=0, Matrix12xcd *B=0, Matrix12Xd *C=0)
double SympStep (double t, UuvState &xb, const UuvState &xa, const Vectorcd &u, double h, const VectorXd *p=0, Matrix12d *A=0, Matrix12xcd *B=0, Matrix12Xd *C=0)
double EulerStep (double t, UuvState &xb, const UuvState &xa, const Vectorcd &u, double h, const VectorXd *p=0, Matrix12d *A=0, Matrix12xcd *B=0, Matrix12Xd *C=0)
Static Public Member Functions
static void Compute (Matrix6d &I, double m, const Vector3d &ds)
Public Attributes
Matrix6d I
6x6 inertia matrix
Vector6d d
6x1 decoupled quadratic drag terms
Vector3d b
center of boyancy
Vector3d fp
constant position force in spatial frame (e.g. due to gravity)
Matrix6xcd B
control input transformation
bool symp
symplectic?
string name
Unique name of the body.
Vector3d ds
body dimensions (currently used only for visualization)
Detailed Description
template<int c = 6>
class gcop::Uuv< c >
An underwater/sufrace vehicle system modeled as a single rigid body on SE(3)
Author: Marin Kobilarov marin(at)jhu.edu
Constructor & Destructor Documentation
template<int c> gcop::Uuv< c >::Uuv ()
References gcop::Uuv< c >::Compute(), gcop::Uuv< c >::ds, and gcop::Uuv< c >::I.
template<int c> gcop::Uuv< c >::~Uuv () [virtual]
Member Function Documentation
template<int c> void gcop::Uuv< c >::Compute (Matrix6d & I, double m, const Vector3d & ds) [static]
Referenced by gcop::Uuv< c >::Uuv().
template<int c> double gcop::Uuv< c >::EulerStep (double t, UuvState & xb, const UuvState & xa, const Vectorcd & u, double h, const VectorXd * p = 0, Matrix12d * A = 0, Matrix12xcd * B = 0, Matrix12Xd * C = 0)
template<int c> double gcop::Uuv< c >::Step (UuvState & xb, double t, const UuvState & xa, const Vectorcd & u, double h, const VectorXd * p = 0, Matrix12d * A = 0, Matrix12xcd * B = 0, Matrix12Xd * C = 0)
template<int c> double gcop::Uuv< c >::SympStep (double t, UuvState & xb, const UuvState & xa, const Vectorcd & u, double h, const VectorXd * p = 0, Matrix12d * A = 0, Matrix12xcd * B = 0, Matrix12Xd * C = 0)
References gcop::SE3::ad(), gcop::SE3::adt(), gcop::SE3::cay(), gcop::UuvState::g, gcop::SE3::Instance(), gcop::SE3::tln(), and gcop::UuvState::v.
Member Data Documentation
template<int c = 6> Vector3d gcop::Uuv< c >::b
center of boyancy
template<int c = 6> Matrix6xcd gcop::Uuv< c >::B
control input transformation
template<int c = 6> Vector6d gcop::Uuv< c >::d
6x1 decoupled quadratic drag terms
template<int c = 6> Vector3d gcop::Uuv< c >::ds
body dimensions (currently used only for visualization)
Referenced by gcop::Uuv< c >::Uuv().
template<int c = 6> Vector3d gcop::Uuv< c >::fp
constant position force in spatial frame (e.g. due to gravity)
template<int c = 6> Matrix6d gcop::Uuv< c >::I
6x6 inertia matrix
Referenced by gcop::Uuv< c >::Uuv().
template<int c = 6> string gcop::Uuv< c >::name
Unique name of the body.
template<int c = 6> bool gcop::Uuv< c >::symp
symplectic?
The documentation for this class was generated from the following file:
lib/systems/uuv.h