GCOP: gcop::Body2dManifold Class Reference
gcop::Body2dManifold Class Reference
#include <body2dmanifold.h>
Public Member Functions
void Lift (Vector6d &dx, const Body2dState &xa, const Body2dState &xb)
void Retract (Body2dState &xb, const Body2dState &xa, const Vector6d &dx)
void dtau (Matrix6d &M, const Vector6d &v)
void Adtau (Matrix6d &M, const Vector6d &v)
Static Public Member Functions
static Body2dManifold & Instance ()
Member Function Documentation
void Body2dManifold::Adtau (Matrix6d & M, const Vector6d & v)
void Body2dManifold::dtau (Matrix6d & M, const Vector6d & v)
Body2dManifold & Body2dManifold::Instance () [static]
Referenced by Lift(), and Retract().
void Body2dManifold::Lift (Vector6d & dx, const Body2dState & xa, const Body2dState & xb)
References Instance().
void Body2dManifold::Retract (Body2dState & xb, const Body2dState & xa, const Vector6d & dx)
References Instance().
The documentation for this class was generated from the following files:
lib/systems/manifolds/body2dmanifold.h
lib/systems/manifolds/body2dmanifold.cc