GCOP: gcop_urdf Namespace Reference
gcop_urdf Namespace Reference
Classes
class Color
class Vector3
class Rotation
class Pose
class JointDynamics
class JointLimits
class JointSafety
Parameters for Joint Safety Controllers.
class JointCalibration
class JointMimic
class Joint
class Geometry
class Sphere
class Box
class Cylinder
class Mesh
class Material
class Inertial
class Visual
class Collision
class Link
class ModelInterface
Functions
bulletmbsgenerator (const string &xml_string, gcop::Matrix4d &gposei_root, string type,)
mbsgenerator (const std::string &xml_string, gcop::Matrix4d &gposei_root, std::string type="FLOATBASE")
boost::shared_ptr< ModelInterface > parseURDF (const std::string &xml_string)
void transformtoprincipal (boost::shared_ptr< Link > link)
void combineinertia (boost::shared_ptr< Link > clink, boost::shared_ptr< Link > plink, Pose posec_p)
void assign (boost::shared_ptr< const Link > link, boost::shared_ptr< Link > parentlink, Pose cumpose)
void aggregate (boost::shared_ptr< const Link > link, boost::shared_ptr< Link > parentlink, Pose cumpose)
gcop::Matrix4d diffpose (Pose &posej_p, Pose &posei_p)
void walkTree (boost::shared_ptr< Link > link, int level, int &index, boost::shared_ptr< gcop::Mbs > mbs)
Function Documentation
void gcop_urdf::aggregate (boost::shared_ptr< const Link > link, boost::shared_ptr< Link > parentlink, Pose cumpose)
Referenced by bulletmbsgenerator().
void gcop_urdf::assign (boost::shared_ptr< const Link > link, boost::shared_ptr< Link > parentlink, Pose cumpose)
Referenced by bulletmbsgenerator().
gcop_urdf::bulletmbsgenerator (const string & xml_string, gcop::Matrix4d & gposei_root, string type)
References aggregate(), assign(), gcop_urdf::Pose::clear(), gcop::SE3::Instance(), parseURDF(), gcop::SE3::quatxyz2g(), transformtoprincipal(), and walkTree().
void gcop_urdf::combineinertia (boost::shared_ptr< Link > clink, boost::shared_ptr< Link > plink, Pose posec_p)
gcop::Matrix4d gcop_urdf::diffpose (Pose & posej_p, Pose & posei_p)
boost::shared_ptr< gcop::Mbs > gcop_urdf::mbsgenerator (const std::string & xml_string, gcop::Matrix4d & gposei_root, std::string type = "FLOATBASE")
boost::shared_ptr<ModelInterface> gcop_urdf::parseURDF (const std::string & xml_string)
Referenced by bulletmbsgenerator().
void gcop_urdf::transformtoprincipal (boost::shared_ptr< Link > link)
Referenced by bulletmbsgenerator().
void gcop_urdf::walkTree (boost::shared_ptr< Link > link, int level, int & index, boost::shared_ptr< gcop::Mbs > mbs)
Referenced by bulletmbsgenerator().