GCOP: lib/utils/params.cc File Reference
params.cc File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <sstream>
#include "params.h"
Functions
static void replace (std::string &str, const std::string &a, const std::string &b)
static void Trim (string &str)
static void Tokenize (const string &str, vector< string > &tokens, const string &delimiters=" ")
Function Documentation
static void replace (std::string & str, const std::string & a, const std::string & b) [static]
Referenced by gcop::Params::GetDouble(), gcop::Params::GetDoubleArray(), gcop::Params::GetDoubleVec(), gcop::Params::GetFloat(), gcop::Params::GetFloatArray(), gcop::Params::GetMatrix6d(), gcop::Params::GetVector2d(), gcop::Params::GetVector3d(), gcop::Params::GetVector4d(), gcop::Params::GetVector5d(), gcop::Params::GetVector6d(), and gcop::Params::GetVectorXd().
static void Tokenize (const string & str, vector< string > & tokens, const string & delimiters = " ") [static]
Referenced by gcop::Params::GetDoubleArray(), gcop::Params::GetDoubleVec(), gcop::Params::GetFloatArray(), gcop::Params::GetMatrix6d(), gcop::Params::GetVector2d(), gcop::Params::GetVector3d(), gcop::Params::GetVector4d(), gcop::Params::GetVector5d(), gcop::Params::GetVector6d(), and gcop::Params::GetVectorXd().
static void Trim (string & str) [static]