GCOP: lib/views/viewer.cc File Reference
viewer.cc File Reference
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <iostream>
#include <cmath>
#include <unistd.h>
#include "utils.h"
#include "viewer.h"
Defines
#define LIGHTX (1.0f)
#define LIGHTY (0.4f)
Functions
void g_viewer_reshape (int w, int h)
void g_viewer_render ()
void g_viewer_keyboard (unsigned char ch, int x, int y)
void g_viewer_mouse (int button, int state, int x, int y)
void g_viewer_motion (int x, int y)
void g_viewer_idle (void)
void g_timer_func (int)
void g_save_frames (int)
void InitViewerWindow ()
Define Documentation
#define LIGHTX (1.0f)
#define LIGHTY (0.4f)
Function Documentation
void g_save_frames (int i)
void g_timer_func (int ms)
void g_viewer_idle (void)
Referenced by gcop::Viewer::Init().
void g_viewer_keyboard (unsigned char ch, int x, int y)
Referenced by gcop::Viewer::Init().
void g_viewer_motion (int x, int y)
Referenced by gcop::Viewer::Init().
void g_viewer_mouse (int button, int state, int x, int y)
Referenced by gcop::Viewer::Init().
void g_viewer_render ()
Referenced by gcop::Viewer::Init().
void g_viewer_reshape (int w, int h)
Referenced by gcop::Viewer::Init().
void InitViewerWindow ()
Referenced by gcop::Viewer::Init().